### ISSUE TITLE
QuoteGenerationSample return error 0xe044

### ISSUE THREAD

**Issue by a3213105** [intel/SGXDataCenterAttestationPrimitives#183]
1 QuoteGenerationSample
root@icx04:~/SGXDataCenterAttestationPrimitives/SampleCode/QuoteGenerationSample# ./app
sgx_qe_set_enclave_load_policy is valid in in-proc mode only and it is optional: the default enclave load policy is persistent:
set the enclave load policy as persistent:succeed!

[get_platform_quote_cert_data ../qe_logic.cpp:346] Error returned from the p_sgx_get_quote_config API. 0xe044
Step1: Call sgx_qe_get_target_info:Error in sgx_qe_get_target_info. 0xe044

2 PCCS log
root@icx04:/opt/intel/sgx-dcap-pccs/logs# cat pccs_server.log
2021-07-06 08:17:06.144 [info]: HTTPS Server is running on: https://localhost:8081
2021-07-06 08:17:25.734 [info]: Client Request-ID : b955c219eb0543ca84203e1f23e393d7
2021-07-06 08:17:25.745 [debug]: https://api.trustedservices.intel.com/sgx/certification/v3/pckcerts
2021-07-06 08:17:25.746 [debug]: {"searchParams":{"encrypted_ppid":"2F2CE0AEE98628062783578FA3F430FDC50678DCEC572361C47B7C4AB32BF8BBC397DCBD1514C3D573F64FCE47E1B8B20C53113CCD5295BA2A8DF0B06B4BEC692CE3FF1ECB31069F927981843FADEB970B955228B70E23899633D15DEF758EFFCA3D430B90F38F826E2B8972D53ED42A02EFED60F4D94C816DC5B91F94E87437160267CBAB85D3AEA141107A457CA089633CE877BB918210969204996B7BB34D7F3EC6E737B393BD59B4A0A5BD4C5DD421EE4EDA6488C9FB9823D3FCAE95F40E63F5A9527955362617B01C418E8B788CD2E4C1FE7AC98606A6FDE39FA48C88245F3BED52499AB463F0B17B667951A02809EFA49CE2599A62D393A0337E166A75CB61B3910483340E7E2034A6B5B0B6B3FD3C6B736FC2823183E596E690378379356BABCEF6349FAEFB7A235924A98043EA42CA5B836B666D50C6614B2796D3BCB07F1D1D19A5D1CCA55AEAA1875AFB1F635D1C145319A1198744F60541CC4A2422ACB7F99EFB6537A8349B2FD9BEEDB60B3E5B9291DEF8896250628C98D67EAA","pceid":"0000"},"method":"GET","headers":{"Ocp-Apim-Subscription-Key":"03baabb994ce4975a8be3d215162613c"}}
2021-07-06 08:17:26.915 [debug]: Response code 404 (Not Found)
2021-07-06 08:17:26.916 [info]: Request-ID is : 9134c304e69d4768b1a3d801c7bd1766
2021-07-06 08:17:26.917 [error]: Error: Unable to retrieve the collateral from the Intel SGX PCS.
    at do_request (/opt/intel/sgx-dcap-pccs/pcs_client/pcs_client.js:70:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Proxy.getPckCertFromPCS (/opt/intel/sgx-dcap-pccs/services/logic/commonCacheLogic.js:81:22)
    at async LazyCachingMode.getPckCertFromPCS (/opt/intel/sgx-dcap-pccs/services/caching_modes/cachingMode.js:122:12)
    at async Proxy.getPckCert (/opt/intel/sgx-dcap-pccs/services/pckcertService.js:114:16)
    at async getPckCert (/opt/intel/sgx-dcap-pccs/controllers/pckcertController.js:71:25)
2021-07-06 08:17:26.925 [info]: 127.0.0.1 - - [06/Jul/2021:08:17:26 +0000] "GET /sgx/certification/v3/pckcert?qeid=5870259CA0B515141FBFF2B7D1763692&encrypted_ppid=2F2CE0AEE98628062783578FA3F430FDC50678DCEC572361C47B7C4AB32BF8BBC397DCBD1514C3D573F64FCE47E1B8B20C53113CCD5295BA2A8DF0B06B4BEC692CE3FF1ECB31069F927981843FADEB970B955228B70E23899633D15DEF758EFFCA3D430B90F38F826E2B8972D53ED42A02EFED60F4D94C816DC5B91F94E87437160267CBAB85D3AEA141107A457CA089633CE877BB918210969204996B7BB34D7F3EC6E737B393BD59B4A0A5BD4C5DD421EE4EDA6488C9FB9823D3FCAE95F40E63F5A9527955362617B01C418E8B788CD2E4C1FE7AC98606A6FDE39FA48C88245F3BED52499AB463F0B17B667951A02809EFA49CE2599A62D393A0337E166A75CB61B3910483340E7E2034A6B5B0B6B3FD3C6B736FC2823183E596E690378379356BABCEF6349FAEFB7A235924A98043EA42CA5B836B666D50C6614B2796D3BCB07F1D1D19A5D1CCA55AEAA1875AFB1F635D1C145319A1198744F60541CC4A2422ACB7F99EFB6537A8349B2FD9BEEDB60B3E5B9291DEF8896250628C98D67EAA&cpusvn=03050100000000000000000000000000&pcesvn=0A00&pceid=0000 HTTP/1.1" 504 57 "-" "-"

3 
root@icx04:/opt/intel/sgx-ra-service# ./mpa_manage -get_registration_status
Registration process completed successfully.

4. MPA log
root@icx04:~/SGXDataCenterAttestationPrimitives/SampleCode/QuoteGenerationSample# cat /var/log/mpa_registration.log
[06-07-2021 08:20:31] INFO: SGX Registration Agent version: 1.10.103.1
[06-07-2021 08:20:31] INFO: Starts Registration Agent Flow.
[06-07-2021 08:20:31] INFO: Registration Flow - Registration status indicates registration is completed successfully. MPA has nothing to do.
[06-07-2021 08:20:31] INFO: Finished Registration Agent Flow.

**Comment by a3213105** [comment]
i think the PCCS log shows that Intel PCS doesn't have my server info. but the MPA log shows registration process completed,
So my question is how can i successfully register my server in Intel PCS and check the status ?

**Comment by a3213105** [comment]
update bios and set server to sbx

**Comment by TY-cc** [comment]
Hi, how to install the mpa? i don't konw the way to install and use it
