### ISSUE TITLE
Manifest successfully registered but pccs failed to pass PCKSelection.

### ISSUE THREAD

**Issue by Ruide** [intel/SGXDataCenterAttestationPrimitives#184]
Hi,

I add code to print out my PCK in PCCS. I have 4 PCK certs in pccs DB. And I parse the 4 PCK certs and find out the 1.2.840.113741.1.13.1.1 OID field is correctly using my correct plaintext PPID (received from registration before). Part of the pccs log is posted below:

<pre>
2021-07-10 21:12:32.908 [info]: Client Request-ID : 05a696f74abf4698923876c4a9e1fad8
2021-07-10 21:12:38.070 [info]: Request-ID is : ed52f1c7e85d40dfbecf67ba36abd80b
2021-07-10 21:12:38.844 [info]: Request-ID is : 94790b768b404861a29244dea1f6afa8
2021-07-10 21:12:38.871 [info]: pce_id: 0
2021-07-10 21:12:38.872 [info]: pce_svn: 11
2021-07-10 21:12:38.872 [info]: cpu_svn: [object Object]
2021-07-10 21:12:38.872 [info]: tcb_info: {"tcbInfo":{"version":2,"issueDate":"2021-07-10T12:04:02Z","nextUpdate":"2021-08-09T12:04:02Z","fmspc":"00606A000000","pceId":"0000","tcbType":0,"tcbEvaluationDataNumber":11,"tcbLevels":[{"tcb":{"sgxtcbcomp01svn":4,"sgxtcbcomp02svn":4,"sgxtcbcomp03svn":3,"sgxtcbcomp04svn":3,"sgxtcbcomp05svn":255,"sgxtcbcomp06svn":255,"sgxtcbcomp07svn":0,"sgxtcbcomp08svn":0,"sgxtcbcomp09svn":0,"sgxtcbcomp10svn":0,"sgxtcbcomp11svn":0,"sgxtcbcomp12svn":0,"sgxtcbcomp13svn":0,"sgxtcbcomp14svn":0,"sgxtcbcomp15svn":0,"sgxtcbcomp16svn":0,"pcesvn":11},"tcbDate":"2021-06-09T00:00:00Z","tcbStatus":"UpToDate"},{"tcb":{"sgxtcbcomp01svn":4,"sgxtcbcomp02svn":4,"sgxtcbcomp03svn":3,"sgxtcbcomp04svn":3,"sgxtcbcomp05svn":255,"sgxtcbcomp06svn":255,"sgxtcbcomp07svn":0,"sgxtcbcomp08svn":0,"sgxtcbcomp09svn":0,"sgxtcbcomp10svn":0,"sgxtcbcomp11svn":0,"sgxtcbcomp12svn":0,"sgxtcbcomp13svn":0,"sgxtcbcomp14svn":0,"sgxtcbcomp15svn":0,"sgxtcbcomp16svn":0,"pcesvn":10},"tcbDate":"2020-11-11T00:00:00Z","tcbStatus":"OutOfDate"},{"tcb":{"sgxtcbcomp01svn":3,"sgxtcbcomp02svn":3,"sgxtcbcomp03svn":3,"sgxtcbcomp04svn":3,"sgxtcbcomp05svn":255,"sgxtcbcomp06svn":255,"sgxtcbcomp07svn":0,"sgxtcbcomp08svn":0,"sgxtcbcomp09svn":0,"sgxtcbcomp10svn":0,"sgxtcbcomp11svn":0,"sgxtcbcomp12svn":0,"sgxtcbcomp13svn":0,"sgxtcbcomp14svn":0,"sgxtcbcomp15svn":0,"sgxtcbcomp16svn":0,"pcesvn":10},"tcbDate":"2020-06-10T00:00:00Z","tcbStatus":"OutOfDate"},{"tcb":{"sgxtcbcomp01svn":3,"sgxtcbcomp02svn":3,"sgxtcbcomp03svn":3,"sgxtcbcomp04svn":3,"sgxtcbcomp05svn":255,"sgxtcbcomp06svn":255,"sgxtcbcomp07svn":0,"sgxtcbcomp08svn":0,"sgxtcbcomp09svn":0,"sgxtcbcomp10svn":0,"sgxtcbcomp11svn":0,"sgxtcbcomp12svn":0,"sgxtcbcomp13svn":0,"sgxtcbcomp14svn":0,"sgxtcbcomp15svn":0,"sgxtcbcomp16svn":0,"pcesvn":5},"tcbDate":"2018-01-04T00:00:00Z","tcbStatus":"OutOfDate"}]},"signature":"a5746d8a2c128c5f3e5e15a8e7575d780d8149934199226abf394520019797d92bbbfbe491a2a35b09ac90dff30dbd770b90d079a3d9882a3dc2204e34793c65"}
2021-07-10 21:12:38.872 [info]: ncerts: 4
2021-07-10 21:12:38.876 [error]: PCK selection library returned 12
2021-07-10 21:12:38.876 [error]: Error: No cache data for this platform.
    at Proxy.getPckCertFromPCS (/data00/intel/sgx-dcap-pccs/services/logic/commonCacheLogic.js:232:11)
    at async LazyCachingMode.registerPlatforms (/data00/intel/sgx-dcap-pccs/services/caching_modes/cachingMode.js:159:7)
    at async Proxy.registerPlatforms (/data00/intel/sgx-dcap-pccs/services/platformsRegService.js:107:3)
    at async postPlatforms (/data00/intel/sgx-dcap-pccs/controllers/platformsController.js:40:5)
2021-07-10 21:12:38.879 [info]: 127.0.0.1 - - [10/Jul/2021:13:12:38 +0000] "POST /sgx/certification/v3/platforms HTTP/1.1" 404 32 "-" "-"
</pre>

Also, my cpusvn and pceid from PCKIDRetrievalTool is posted as following:

<pre>
 PCE_ID:
0000
 TCBr - CPUSVN:
050502ffffff00000000000000000000
 TCBr - PCE_ISVSVN:
0b00
</pre>

Could someone help me with this situation? 

pccs seems to have successfully fetched the PCK certs, while pccs seems to reject the TCB version? Why is PCK selection library rejecting the settings? 

Thank you!

**Comment by Ruide** [comment]
The 050502ffffff00000000000000000000 tcb version is too low. Need to be at least 050503ffffff00000000000000000000.

**Comment by jsun39** [comment]
I supposed the hardware was one ICX-SP platform. Based on your CPU_SVN's value, it seems that your BIOS has some problem, please update your BIOS.

**Comment by lili8808** [comment]
I faced the same issue I am using Azure Virtual Machine with kernel :
`Linux version 5.15.0-1029-azure (buildd@lcy02-amd64-076) (gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #36~20.04.1-Ubuntu SMP Tue Dec 6 17:00:26 UTC 2022`
and CPU:
```
description: CPU
       product: Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
       vendor: Intel Corp.
       physical id: 4
       bus info: cpu@0
       version: Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
       serial: None
       slot: None
       size: 3456MHz
       capacity: 3500MHz
       width: 64 bits
       clock: 100MHz
       capabilities: lm fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp x86-64 constant_tsc rep_good nopl xtopology tsc_reliable nonstop_tsc cpuid aperfmperf pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single fsgsbase tsc_adjust sgx bmi1 hle avx2 smep bmi2 erms invpcid rtm avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves avx512vbmi umip avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq la57 rdpid sgx_lc fsrm arch_capabilities cpufreq
       configuration: cores=1 enabledcores=1 threads=1
```
and when I run the command `PCKIDRetrievalTool` I get : ```
Intel(R) Software Guard Extensions PCK Cert ID Retrieval Tool Version 1.15.100.3

Warning: platform manifest is not available or current platform is not multi-package platform.
Error: unexpected error occurred while sending data to cache server.
pckid_retrieval.csv has been generated successfully, however the data couldn't be sent to cache server! 
```
while in my pccs_server.log I have:
```
2022-12-28 10:49:46.165 [info]: Client Request-ID : eb449da2df1a4679a43c742859ba0f5c
2022-12-28 10:49:46.571 [info]: Request-ID is : d551ca690952403aaa02ce6bebb974ac
2022-12-28 10:49:46.571 [error]: Intel PCS server returns error(404).
2022-12-28 10:49:46.571 [error]: Intel PCS server returns error. Error code : 404
2022-12-28 10:49:46.571 [error]: Error: No cache data for this platform.
    at Module.getPckCertFromPCS (file:///opt/intel/sgx-dcap-pccs/services/logic/commonCacheLogic.js:92:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ReqCachingMode.registerPlatforms (file:///opt/intel/sgx-dcap-pccs/services/caching_modes/cachingMode.js:205:7)
    at async Module.registerPlatforms (file:///opt/intel/sgx-dcap-pccs/services/platformsRegService.js:107:3)
    at async postPlatforms (file:///opt/intel/sgx-dcap-pccs/controllers/platformsController.js:40:5)
2022-12-28 10:49:46.576 [info]: 127.0.0.1 - - [28/Dec/2022:10:49:46 +0000] "POST /sgx/certification/v3/platforms HTTP/1.1" 404 32 "-" "-"
```
I have no idea why this happens?

**Comment by Ruide** [comment]
> 

Please check the following page. You should be able to find them in the output file.
https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/master/tools/PCKRetrievalTool/README.build

**Comment by lili8808** [comment]
Thanks , for me CPUSVN is :
08090e0dffff01000000000000000000
and PCE ISVSVN is:
0d00
and QE_ID is:
14ea436ba80fa16fd5a7e510cbcfddd8
How ever I get error No cache data for this platform. 
do you where is the issue? should I update the BIOS? is it possible that TCB is not enabled on my BIOS? Do you know how can I check it?

**Comment by Ruide** [comment]
> @Ruide Thanks , for me CPUSVN is :
> 
> 08090e0dffff01000000000000000000
> 
> and PCE ISVSVN is:
> 
> 0d00
> 
> and QE_ID is:
> 
> 14ea436ba80fa16fd5a7e510cbcfddd8
> 
> How ever I get error No cache data for this platform. 
> 
> do you where is the issue? should I update the BIOS? is it possible that TCB is not enabled on my BIOS? Do you know how can I check it?
> 
> 

You can use api here to debug. https://api.portal.trustedservices.intel.com/documentation#pcs-certificate-v3. If these work, Then the issue is with your pccs service. pccs service is a cache for the apis i mentioned above.

**Comment by jsun39** [comment]
What is your platform type? ICX-SP?
