### ISSUE TITLE
unexpected error happend during sending data to cache server

### ISSUE THREAD

**Issue by Keepmoving-ZXY** [intel/SGXDataCenterAttestationPrimitives#187]
Today I run `PCKIDRetrievalTool` and version of this tool is `1.10.103.1`, then I receive an error message:
```
[root@localhost PCKIDRetrievalTool_v1.10.103.1]# ./PCKIDRetrievalTool 

Intel(R) Software Guard Extensions PCK Cert ID Retrieval Tool Version 1.10.103.1

Error: unexpected error happend during sending data to cache server.
Registration status has been set to completed status.
pckid_retrieval.csv has been generated successfully, however the data couldn't be sent to cache server!
``` 
And this error message shows that error may occurs in pccs, and I do find error in pccs log:
```
[pccs@localhost ~]$ node -r esm pccs_server.js 
morgan deprecated default format: use combined format node_modules/esm/esm.js:1:278827
https://api.trustedservices.intel.com/sgx/certification/v3/
2021-07-13 11:25:55.615 [info]: HTTPS Server is running on: https://localhost:8081
2021-07-13 11:26:57.554 [info]: Client Request-ID : 80012af776374646a11ea3890d687e37
2021-07-13 11:26:59.195 [info]: Request-ID is : 1a7c6d5fd3894f55a17633104409cb59
2021-07-13 11:26:59.196 [error]: Error: Unable to retrieve the collateral from the Intel SGX PCS.
    at do_request (/opt/intel/sgx-dcap-pccs/pcs_client/pcs_client.js:70:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2021-07-13 11:26:59.198 [info]: 127.0.0.1 - - [13/Jul/2021:03:26:59 +0000] "POST /sgx/certification/v3/platforms HTTP/1.1" 504 57 "-" "-"
```
I google this error, and find issue  [#153](https://github.com/intel/SGXDataCenterAttestationPrimitives/issues/153) provide some solution to this error, but don't take effect to me.
This is `lscpu` of my workstation:
```
[root@localhost rpm]# lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              112
On-line CPU(s) list: 0-111
Thread(s) per core:  2
Core(s) per socket:  28
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               106
Model name:          Montage Jintide(R) C6330
Stepping:            6
CPU MHz:             3009.886
CPU max MHz:         3100.0000
CPU min MHz:         800.0000
BogoMIPS:            4000.00
Virtualization:      VT-x
L1d cache:           48K
L1i cache:           32K
L2 cache:            1280K
L3 cache:            43008K
NUMA node0 CPU(s):   0-27,56-83
NUMA node1 CPU(s):   28-55,84-111
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid md_clear pconfig flush_l1d arch_capabilities
```
Could you help me to solve this error?

**Comment by Keepmoving-ZXY** [comment]
And in pccs's default.json, `uri` is set to `https://sbx.api.trustedservices.intel.com/sgx/certification/v3/`, then `ApiKey` is set to primary key in `Product SBX Intel® Software Guard Extensions Provisioning Certification`.

**Comment by jsun39** [comment]
Do you know your platform is production or pre-production platform?  From your message, it seems that your platform was pre-production platform, however basically pre-production should not be in public market.  

So if your platform was pre-production platform, please contact your platform vendor.  It need do additional work to resolve this issue. 

Otherwise please use the production server's URL: https://api.trustedservices.intel.com/sgx/certification/v3/

**Comment by Keepmoving-ZXY** [comment]
The workstation is borrowed from another partner, they provide us a pre-production platform for little time's use. And I have another thing to confirm. In the Intel's public paper `Supporting Third Party Attestation for Intel® SGX
with Intel® Data Center Attestation Primitives`, Intel introduct how the third party attestation run, and the parper don't mention that whether the relying party should be a SGX2 compatible platform or not, could you help me make sense it?

**Comment by jsun39** [comment]
OK, please contact your partner. For you last question, the answer is NO. Attestation does NOT depends on SGX2.

**Comment by Keepmoving-ZXY** [comment]
ok，thank you.
