### ISSUE TITLE
Error: Unable to retrieve the collateral from the Intel SGX PCS.

### ISSUE THREAD

**Issue by Keepmoving-ZXY** [intel/SGXDataCenterAttestationPrimitives#197]
Yesterday, our company's SGX2 workstation is ready to use and I spend some time to install sgx driver, sdk and other rpm package downloading from 01.org. Today I encounter a error during quote generation, the output of PCCS is:
```
2021-09-01 19:27:42.700 [info]: HTTPS Server is running on: https://localhost:8081
2021-09-01 19:28:12.399 [info]: Client Request-ID : 449b8279905e4877bc807c875dd76bdd
2021-09-01 19:28:12.405 [debug]: https://api.trustedservices.intel.com/sgx/certification/v3/pckcerts
2021-09-01 19:28:12.405 [debug]: {"searchParams":{"encrypted_ppid":"776559A9E1E93B5FCFADC10CBD2C03A7AC05B797304F8AFF5D43C30980EFAB154B1AE95F59B864DCBECA78AE9AE05FCC2227EDC0BE5CA7D386218A79CEFA99D9DFDBFB2FF98C689E9BCFC11CFE6885A84FAEBDF6459A71DCBCC184A0EE0EA82C65BCA298AB2C45CE7D2756D38ED552CF284D22A2E2781AAA125880AE44C65370A4A251979F6CCD6DC1A821CF71EA4D5B3F83FB2D93E35BCA31442220BC21B22B7FF638A1EC8529F8E98C3F5CAF29A04BB5EEFF16E7E5B63935FA47698F98E48E36A30D62C136B1F9A954C5542B6747220514475F9809F009CCEBD039C9CCF3FF7C176B6514308CAF468B69619D866FF093E34C84F1AEAF6798D0D3E7308746206B27C8DCF0D8EC80A263393AE0A407146EFA15D60367CBAF8ABD85924DF793EA0CEF816AB12DFAC5066FB940C39D4B3208DE4AA68832B77AF009E6C60C279F3DED17382E135AD782E1D95EF2A5BC56635247119C2FA710B63EDFAE6DF5C8994C9B74FE280C0133885EFB6D1E425F5B248C51A9AF8F54DE666DE88F9D93F21F73","pceid":"0000"},"method":"GET","headers":{"Ocp-Apim-Subscription-Key":"6a0f5***"}}
2021-09-01 19:28:13.713 [debug]: Response code 404 (Not Found)
2021-09-01 19:28:13.713 [info]: Request-ID is : 9416104e3299428c854a904d1bb78cba
2021-09-01 19:28:13.714 [error]: Error: Unable to retrieve the collateral from the Intel SGX PCS.
    at do_request (/opt/intel/sgx-dcap-pccs/pcs_client/pcs_client.js:79:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Proxy.getPckCertFromPCS (/opt/intel/sgx-dcap-pccs/services/logic/commonCacheLogic.js:81:22)
    at async LazyCachingMode.getPckCertFromPCS (/opt/intel/sgx-dcap-pccs/services/caching_modes/cachingMode.js:126:12)
    at async Proxy.getPckCert (/opt/intel/sgx-dcap-pccs/services/pckcertService.js:114:16)
    at async getPckCert (/opt/intel/sgx-dcap-pccs/controllers/pckcertController.js:71:25)
2021-09-01 19:28:13.716 [info]: 127.0.0.1 - - [01/Sep/2021:11:28:13 +0000] "GET /sgx/certification/v3/pckcert?qeid=4C21B5EA9FA45AA42470F136D823D8C3&encrypted_ppid=776559A9E1E93B5FCFADC10CBD2C03A7AC05B797304F8AFF5D43C30980EFAB154B1AE95F59B864DCBECA78AE9AE05FCC2227EDC0BE5CA7D386218A79CEFA99D9DFDBFB2FF98C689E9BCFC11CFE6885A84FAEBDF6459A71DCBCC184A0EE0EA82C65BCA298AB2C45CE7D2756D38ED552CF284D22A2E2781AAA125880AE44C65370A4A251979F6CCD6DC1A821CF71EA4D5B3F83FB2D93E35BCA31442220BC21B22B7FF638A1EC8529F8E98C3F5CAF29A04BB5EEFF16E7E5B63935FA47698F98E48E36A30D62C136B1F9A954C5542B6747220514475F9809F009CCEBD039C9CCF3FF7C176B6514308CAF468B69619D866FF093E34C84F1AEAF6798D0D3E7308746206B27C8DCF0D8EC80A263393AE0A407146EFA15D60367CBAF8ABD85924DF793EA0CEF816AB12DFAC5066FB940C39D4B3208DE4AA68832B77AF009E6C60C279F3DED17382E135AD782E1D95EF2A5BC56635247119C2FA710B63EDFAE6DF5C8994C9B74FE280C0133885EFB6D1E425F5B248C51A9AF8F54DE666DE88F9D93F21F73&cpusvn=05050809FFFF00000000000000000000&pcesvn=0B00&pceid=0000 HTTP/1.1" 504 57 "-" "-"
```
The workstation's CPU is `Intel(R) Xeon(R) Gold 6346 CPU`, and is SGX2 compatible processor, and I have  searched this error in github and find some issues about this problem,  but nothing help. Could you help me to solve this problem?

**Comment by Keepmoving-ZXY** [comment]
And the output during quote generation is:
```
[centos@sgx QuoteGenerationSample]$ ./app 
sgx_qe_set_enclave_load_policy is valid in in-proc mode only and it is optional: the default enclave load policy is persistent: 
set the enclave load policy as persistent:succeed!

[get_platform_quote_cert_data ../qe_logic.cpp:377] Error returned from the p_sgx_get_quote_config API. 0xe044
Step1: Call sgx_qe_get_target_info:Error in sgx_qe_get_target_info. 0xe044
```
Does this help?

**Comment by jsun39** [comment]
do you have tried to register the platform?

**Comment by Keepmoving-ZXY** [comment]
The registration systemd service is already run and still has the same error during PCCS retrieve PCK certificatem ad the status of mpa_registration_tool.service is:
```
[centos@sgx QuoteGenerationSample]$ sudo systemctl status mpa_registration_tool.service
● mpa_registration_tool.service - Intel MPA Registration
   Loaded: loaded (/usr/lib/systemd/system/mpa_registration_tool.service; enabled; vendor preset: disa>
   Active: inactive (dead) since Thu 2021-09-02 10:33:51 CST; 3min 5s ago
  Process: 582453 ExecStart=/opt/intel/sgx-ra-service/mpa_registration (code=exited, status=0/SUCCESS)
 Main PID: 582453 (code=exited, status=0/SUCCESS)

Sep 02 10:33:51 sgx systemd[1]: Started Intel MPA Registration.
Sep 02 10:33:51 sgx systemd[1]: mpa_registration_tool.service: Succeeded.
```
Log of this service is:
```
[01-09-2021 03:32:08] INFO: SGX Registration Agent version: 1.11.100.2
[01-09-2021 03:32:08] INFO: Starts Registration Agent Flow.
[01-09-2021 03:32:08] INFO: Registration Flow - Registration status indicates registration is completed successfully. MPA has nothing to do.
[01-09-2021 03:32:08] INFO: Finished Registration Agent Flow.
[02-09-2021 10:29:25] INFO: SGX Registration Agent version: 1.11.100.2
[02-09-2021 10:29:25] INFO: Starts Registration Agent Flow.
[02-09-2021 10:29:25] INFO: Registration Flow - Registration status indicates registration is completed successfully. MPA has nothing to do.
[02-09-2021 10:29:25] INFO: Finished Registration Agent Flow.
[02-09-2021 10:33:16] INFO: SGX Registration Agent version: 1.11.100.2
[02-09-2021 10:33:16] INFO: Starts Registration Agent Flow.
[02-09-2021 10:33:16] INFO: Registration Flow - Registration status indicates registration is completed successfully. MPA has nothing to do.
[02-09-2021 10:33:16] INFO: Finished Registration Agent Flow.
[02-09-2021 10:33:37] INFO: SGX Registration Agent version: 1.11.100.2
[02-09-2021 10:33:37] INFO: Starts Registration Agent Flow.
[02-09-2021 10:33:37] INFO: Registration Flow - Registration status indicates registration is completed successfully. MPA has nothing to do.
[02-09-2021 10:33:37] INFO: Finished Registration Agent Flow.
[02-09-2021 10:33:51] INFO: SGX Registration Agent version: 1.11.100.2
[02-09-2021 10:33:51] INFO: Starts Registration Agent Flow.
[02-09-2021 10:33:51] INFO: Registration Flow - Registration status indicates registration is completed successfully. MPA has nothing to do.
[02-09-2021 10:33:51] INFO: Finished Registration Agent Flow.
```

**Comment by Keepmoving-ZXY** [comment]
@jsun39  It seems that the register service don't have any problem, do you have another idea?

**Comment by jsun39** [comment]
Except MPA, Have you used PCKIDRetrievalTool to collect the platform's information?

**Comment by Keepmoving-ZXY** [comment]
Yes, I have run PCKIDRetrievalTool, this tool report an error:
```
[centos@sgx ~]$ PCKIDRetrievalTool 

Intel(R) Software Guard Extensions PCK Cert ID Retrieval Tool Version 1.11.100.2

Warning: platform manifest is not available or current platform is not multi-package platform.

 Please input the pccs password, and use "Enter key" to end
Error: unexpected error happend during sending data to cache server.
pckid_retrieval.csv has been generated successfully, however the data couldn't be sent to cache server!
```

**Comment by Keepmoving-ZXY** [comment]
Does Intel block my platform， I don't know why PCCS can't retrieve PCK certificate， it's too hard to use.

**Comment by Keepmoving-ZXY** [comment]
Does I need to update BIOS firmware?

**Comment by Keepmoving-ZXY** [comment]
This is the BIOS version information:
![微信图片_20210903175618](https://user-images.githubusercontent.com/19542656/131987310-021a35c2-17d7-4b3b-be38-ddd88fd4d867.png)

**Comment by jdbeaney** [comment]
Based on what you are seeing, I think you have either:

1.  Lost the PlatformManifest required to register: "Warning: platform manifest is not available or current platform is not multi-package platform." Go into your BIOS and perform "SGX Factory Reset" to reset the SGX state.  This will put your platform in the initial SGX registration state.
Also, enable the 'SGX MPA Auto Run'.  This will put your This will allow the MPA to automatically run on boot.  Seems like you have already done this.  This will be the simpler method of registration than using the PCK Cert ID Retrieval Tool.
Boot and then check you MPA log again.

2. Have a pre-production platform.  Do you know the QDF of the CPU(s) in your platform?  The default platform configuration out-of-the-box is set to work for production CPUs.

**Comment by jsun39** [comment]
Another potential reason:
you have done the indirect registration(like using PCKIDRetrieveltool), and retrieve the PCK certs from Intel PCS, however you didn't save these certs, then now you want to use the encryped_ppid to retrieve the PCK certs, thus Intel PCS server will NOT allow it.

So my suggestion: 
1. In the BIOS, please do "SGX Factory reset" operation
2. using MPA to registry the platform
3. then please try to generate the Quote.

By the way, do you have setup your owner PCCS?

**Comment by Keepmoving-ZXY** [comment]
@jdbeaney @jsun39  Enable "SGX Factory Reset‘’ in BIOS take effect, and an error occurs during `PCKIDRetrievalTool` but seems affect nothing, output of this tool is:
```
[centos@sgx QuoteVerificationSample]$ PCKIDRetrievalTool 

Intel(R) Software Guard Extensions PCK Cert ID Retrieval Tool Version 1.11.100.2


 Please input the pccs password, and use "Enter key" to end
Warning: error happens when set registration status, the error code is: 4 
Warning: could NOT set the Registration Status to completed status.
the data has been sent to cache server successfully and pckid_retrieval.csv has been generated successfully!
```
Shuold  the error when set Registration Status be fixed?

**Comment by Keepmoving-ZXY** [comment]
@jsun39 The PCCS is installed by rpm package from intel 01.org, and @jdbeaney the CPU of our platform is `Intel(R) Xeon(R) Gold 6346 CPU @ 3.10GHz`, this CPU isn't a product CPU.

**Comment by jdbeaney** [comment]
I wouldn't expect the error when writing the status register.  This may be a problem with the UEFI variable permissions.  But, it should not affect your ability to perform remote attestation.

Are you able to run the GenerateQuote sample from DCAP?  https://github.com/intel/SGXDataCenterAttestationPrimitives/tree/master/QuoteGeneration

I cannot tell if your platform is pre-production or not based on the information you provided.  Do you have access to the QDF of the processor you are using in your platform?  If your platform is using pre-production CPUs, you will not be able to perform remote attestation out-of-the-box.

**Comment by Keepmoving-ZXY** [comment]
@jdbeaney The GenerateQuote runs well in our SGX2 platform, and I don't know QPF of the processor and how to check it.

**Comment by jdbeaney** [comment]
If you were able to successfully run the GenerateQuote sample, then that confirms your platform has a production CPU.

Have you tried running the VerifyQuote sample as well?

**Comment by Keepmoving-ZXY** [comment]
Yes, the VertifyQuote runs well.
