### ISSUE TITLE
InvalidRegistrationServer on sbx platform

### ISSUE THREAD

**Issue by ardhipoetra** [intel/SGXDataCenterAttestationPrimitives#207]
Hi,

We have a pre-production machine that is supposed to work with the SBX platform. I generated `platform_manifest` by using `PCKIDRetrievalTool` with PCCS server pointing to `https://sbx.api.trustedservices.intel.com/sgx/certification/v3/`. I provided the `ApiKey` as well although not sure if that's matters. 

Using `curl -H "Content-Type: application/octet-stream" -v --data-binary @platform_manifest.bin -X POST "https://sbx.api.trustedservices.intel.com/sgx/registration/v1/platform"` it gives me `InvalidRegistrationServer` error. 
Using [non-sbx](https://api.trustedservices.intel.com/sgx/registration/v1/platform) platform, gives me `PackageNotFound` (which is understandable).

Also note that PCCS logs when I did the PCK retrieval was (I added `Rq` log to make sure I know what is the platform): 
```
2021-11-30 12:05:25.581 [info]: Client Request-ID : b04257627fcf472a90acb491ed28fca5
2021-11-30 12:05:25.583 [info]: Rq: https://sbx.api.trustedservices.intel.com/sgx/certification/v3/pckcerts
2021-11-30 12:05:26.125 [info]: Request-ID is : b29fd75d9c0e4fe99696b2eff40bdf80
2021-11-30 12:05:26.125 [error]: Error: No cache data for this platform.
    at Proxy.getPckCertFromPCS (/opt/intel/sgx-dcap-pccs/services/logic/commonCacheLogic.js:86:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async LazyCachingMode.registerPlatforms (/opt/intel/sgx-dcap-pccs/services/caching_modes/cachingMode.js:163:7)
    at async Proxy.registerPlatforms (/opt/intel/sgx-dcap-pccs/services/platformsRegService.js:107:3)
    at async postPlatforms (/opt/intel/sgx-dcap-pccs/controllers/platformsController.js:40:5)
2021-11-30 12:05:26.126 [info]: 127.0.0.1 - - [30/Nov/2021:11:05:26 +0000] "POST /sgx/certification/v3/platforms HTTP/1.1" 404 32 "-" "-"
```

When I run `QuoteGenerationSample` (which failed on Step1:`Error in sgx_qe_get_target_info. 0xe011`) , PCCS gives me : 
```
2021-11-30 11:55:15.671 [info]: Client Request-ID : e0716b99cb674721bdfb094861e27606
2021-11-30 11:55:15.674 [info]: Rq: https://sbx.api.trustedservices.intel.com/sgx/certification/v3/pckcerts
2021-11-30 11:55:16.209 [info]: Request-ID is : 74f35521a00d412bb3554a26983b3dc5
2021-11-30 11:55:16.210 [error]: Error: No cache data for this platform.
    at Proxy.getPckCertFromPCS (/opt/intel/sgx-dcap-pccs/services/logic/commonCacheLogic.js:86:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async LazyCachingMode.getPckCertFromPCS (/opt/intel/sgx-dcap-pccs/services/caching_modes/cachingMode.js:126:12)
    at async Proxy.getPckCert (/opt/intel/sgx-dcap-pccs/services/pckcertService.js:115:16)
    at async getPckCert (/opt/intel/sgx-dcap-pccs/controllers/pckcertController.js:77:25)
2021-11-30 11:55:16.211 [info]: 127.0.0.1 - - [30/Nov/2021:10:55:16 +0000] "GET /sgx/certification/v3/pckcert?qeid=<redacted>&encrypted_ppid=<redacted>&cpusvn=<redacted>&pcesvn=<redacted>&pceid=<redacted> HTTP/1.1" 404 32 "-" "-"
```

I wonder if I missed some instruction somewhere.

**Comment by jsun39** [comment]
Can you make sure your platform is in production status?  What's the out put for command: rdmsr 0x503?

**Comment by jdbeaney** [comment]
Check to see if your BIOS allows you to change the Registration Server configuration to SBX (default is Auto which only works for production CPUs).

But, in general, our production SW releases only support production platforms by default.  With the changes to the BIOS config (which likely you have not done yet) and the PCKCertIDRetrievalTool/PCCS config (which you have already done) to use SBX, you will be able to successfully generate a Quote.  But, Quote verification will fail by default.  The Quote Verification Library we release only supports verifying quotes from production platforms.

**Comment by ardhipoetra** [comment]
@jsun39, the output is 0. So does it means SGX debug is disabled? 

@jdbeaney, no we don't have that option on the BIOS. The closest one we have is 'Enable/Disable SGX Auto MP Registration Agent', which I assume regarding the multipackage platform. We tried several combinations on BIOS configuration, but it seems nothing comes up to direct registration server to SBX.

**Comment by jsun39** [comment]
If that is the case, you can't change the Registration Server's URL in BIOS, We have another tool(mpa_manage) in OS environment to change the Registration server.  This tool is publicly available, but you still need some data to provide to this tool.  I am not sure which organization you are from, please contact your support/account team to support you to get it.

**Comment by ardhipoetra** [comment]
Thanks for the hint. Yes, that solves it. Using `mpa_manage` solve the 404 on pccs server as well.

**Comment by deliciousdish** [comment]
I have the same problem as the first comment，so how to get server_id and hex_flags when use the mpa_manage to set the Registration Server's URL?
