### ISSUE TITLE
Error returned from the p_sgx_get_quote_config API. 0xe019 when execute QuoteGenerationSample

### ISSUE THREAD

**Issue by deliciousdish** [intel/SGXDataCenterAttestationPrimitives#219]
I got an error when execute QuoteGenerationSample, and have no idea how to solve it. Any suggestions will be appreciated
```
sgx_qe_set_enclave_load_policy is valid in in-proc mode only and it is optional: the default enclave load policy is persistent:
set the enclave load policy as persistent:succeed!

Step1: Call sgx_qe_get_target_info:[get_platform_quote_cert_data ../qe_logic.cpp:347] Error returned from the p_sgx_get_quote_config API. 0xe019
Error in sgx_qe_get_target_info. 0xe019

```
The status of pccs
```
● pccs.service - Provisioning Certificate Caching Service (PCCS)
     Loaded: loaded (/lib/systemd/system/pccs.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2022-03-10 01:27:18 CST; 2h 1min ago
       Docs: https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/master/QuoteGeneration/pccs/README.md
   Main PID: 265316 (node)
      Tasks: 11 (limit: 38113)
     Memory: 57.6M
     CGroup: /system.slice/pccs.service
             └─265316 /usr/bin/node -r esm /opt/intel/sgx-dcap-pccs/pccs_server.js

3月 10 01:27:18 caiqishen-ThinkCentre-M920t-N000 systemd[1]: Started Provisioning Certificate Caching Service (PCCS).
3月 10 01:27:19 caiqishen-ThinkCentre-M920t-N000 node[265316]: Wed, 09 Mar 2022 17:27:19 GMT morgan deprecated default format: use combined format at node_modules/esm/esm.js:1:278827
3月 10 01:27:20 caiqishen-ThinkCentre-M920t-N000 node[265316]: 2022-03-10 01:27:20.035 [info]: HTTPS Server is running on: https://localhost:8081
```
The status of aesmd
```
● aesmd.service - Intel(R) Architectural Enclave Service Manager
     Loaded: loaded (/lib/systemd/system/aesmd.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2022-03-10 01:56:01 CST; 1h 33min ago
   Main PID: 296307 (aesm_service)
      Tasks: 4 (limit: 38113)
     Memory: 2.5M
     CGroup: /system.slice/aesmd.service
             └─296307 /opt/intel/sgx-aesm-service/aesm/aesm_service

3月 10 01:56:01 caiqishen-ThinkCentre-M920t-N000 systemd[1]: Starting Intel(R) Architectural Enclave Service Manager...
3月 10 01:56:01 caiqishen-ThinkCentre-M920t-N000 systemd[1]: Started Intel(R) Architectural Enclave Service Manager.
3月 10 01:56:02 caiqishen-ThinkCentre-M920t-N000 aesm_service[296307]: The server sock is 0x55fa82c21870

```

**Comment by jsun39** [comment]
please make sure your QPL's configuration is correct:  make sure PCCS_URL points to your PCCS

**Comment by deliciousdish** [comment]
> please make sure your QPL's configuration is correct: make sure PCCS_URL points to your PCCS
Hi, thanks for your reply, the content of the /etc/sgx_default_qcnl.conf is as the following:
```
# PCCS server address
PCCS_URL=https://localhost:8081/sgx/certification/v3/

# To accept insecure HTTPS certificate, set this option to FALSE
USE_SECURE_CERT=FALSE

# You can use Intel PCS to get quote verification collateral
#COLLATERAL_SERVICE=https://api.trustedservices.intel.com/sgx/certification/v3/

# If you use PCCS service to get quote verification collateral, you can specify which API version is to be used
# The legacy 3.0 API will return CRLs in HEX encoded DER format, while the new 3.1 API will return raw DER format
#PCCS_API_VERSION=3.1

# Maximum retry times for QCNL. If RETRY is not defined or set to 0, no retry will be performed.
# It will first wait one second and then for all forthcoming retries it will double the waiting time
# By using RETRY_DELAY you disable this exponential backoff algorithm
#RETRY_TIMES=6

# Sleep this amount of seconds before each retry when a transfer has failed with a transient error
#RETRY_DELAY=10
```

**Comment by lingyuj** [comment]
It's recommended that always make sure the PCCS is working correctly by running 
(replace localhost with your server ip)
curl -v -k -G "https://localhost:8081/sgx/certification/v3/rootcacrl"
or
curl --noproxy "*" -v -k -G "https://localhost:8081/sgx/certification/v3/rootcacrl"

**Comment by deliciousdish** [comment]
I run  curl --noproxy "*" -v -k -G "https://localhost:8081/sgx/certification/v3/rootcacrl" and get the following response:
```
*   Trying 127.0.0.1:8081...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8081 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=AU; ST=Some-State; O=Internet Widgits Pty Ltd
*  start date: Mar  8 23:50:17 2022 GMT
*  expire date: Mar  8 23:50:17 2023 GMT
*  issuer: C=AU; ST=Some-State; O=Internet Widgits Pty Ltd
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
> GET /sgx/certification/v3/rootcacrl HTTP/1.1
> Host: localhost:8081
> User-Agent: curl/7.68.0
> Accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Mark bundle as not supporting multiuse
< HTTP/1.1 502 Bad Gateway
< X-Powered-By: Express
< Request-ID: af81d5c251e64ab88cf7da6949e86f72
< Content-Type: text/html; charset=utf-8
< Content-Length: 57
< ETag: W/"39-Sjaqtpr4xLmFO1kPTbY975rx+is"
< Date: Wed, 09 Mar 2022 22:20:59 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
<
* Connection #0 to host localhost left intact

```
It looks like "bad Gateway"?

**Comment by deliciousdish** [comment]
I ran curl --noproxy "*" -v -k -G "https://localhost:8081/sgx/certification/v3/rootcacrl".
I looks like pccs will connect to intel PCS, and got an error, "bad gateway".
The error message in /opt/intel/sgx-dcap-pccs/logs/pccs_server.log is as the following
```
2022-03-10 06:20:59.671 [error]: Error: Unable to retrieve the collateral from the Intel SGX PCS.
    at do_request (/opt/intel/sgx-dcap-pccs/pcs_client/pcs_client.js:81:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /opt/intel/sgx-dcap-pccs/services/logic/commonCacheLogic.js:362:30
    at async /opt/intel/sgx-dcap-pccs/node_modules/sequelize/lib/sequelize.js:1090:24
    at async Proxy.getRootCACrlFromPCS (/opt/intel/sgx-dcap-pccs/services/logic/commonCacheLogic.js:359:10)
    at async LazyCachingMode.getRootCACrlFromPCS (/opt/intel/sgx-dcap-pccs/services/caching_modes/cachingMode.js:145:12)
    at async Proxy.getRootCaCrl (/opt/intel/sgx-dcap-pccs/services/rootcacrlService.js:47:11)
    at async getRootCaCrl (/opt/intel/sgx-dcap-pccs/controllers/rootcacrlController.js:38:21)
2022-03-10 06:20:59.676 [info]: 127.0.0.1 - - [09/Mar/2022:22:20:59 +0000] "GET /sgx/certification/v3/rootcacrl HTTP/1.1" 502 57 "-" "curl/7.68.0"
```

**Comment by andyzyb** [comment]
Is this because you don't specify the proxy in pccs configuration file so it fails to connect Intel PCS service?

**Comment by deliciousdish** [comment]
It indeed has a proxy in my network, but i have set proxy in /opt/intel/sgx-dcap-pccs/config/default.json. I will continue to solve this problem using other http client, curl or postman. Thanks to all.

**Comment by deliciousdish** [comment]
I execute the following command:
```
curl -v -X GET "https://api.trustedservices.intel.com/sgx/certification/v3/pckcert?encrypted_ppid={}&cpusvn={}&pcesvn={}&pceid={}" -H "Ocp-Apim-Subscription-Key: {subscription key}" 
```
and got an error message
```
Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription
```
when I subscribe "Intel® Software Guard Extensions Provisioning Certification Service", I got a primary key and Secondary key.
I use the primary key as the subscription key, is that right?

**Comment by lingyuj** [comment]
Yes, you can use either of them.

**Comment by deliciousdish** [comment]
Now I can get pckcert using curl, but when running  curl --noproxy "*" -v -k -G "https://localhost:8081/sgx/certification/v3/rootcacrl", i will get a 502 error code.  It looks like intel does not provide this api according to https://api.portal.trustedservices.intel.com/documentation#pcs-certificates-v3

**Comment by lingyuj** [comment]
This API is provided by PCCS, not Intel PCS. Can you post the last log of PCCS?

**Comment by deliciousdish** [comment]
The last log of PCCS is as the following:
```
2022-03-10 08:43:13.074 [info]: Client Request-ID : 296955ac870e41908d1a7eb4d7bba3a7
2022-03-10 08:43:14.185 [debug]: self signed certificate in certificate chain
2022-03-10 08:43:14.186 [error]: Error: Unable to retrieve the collateral from the Intel SGX PCS.
    at do_request (/opt/intel/sgx-dcap-pccs/pcs_client/pcs_client.js:81:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /opt/intel/sgx-dcap-pccs/services/logic/commonCacheLogic.js:362:30
    at async /opt/intel/sgx-dcap-pccs/node_modules/sequelize/lib/sequelize.js:1090:24
    at async Proxy.getRootCACrlFromPCS (/opt/intel/sgx-dcap-pccs/services/logic/commonCacheLogic.js:359:10)
    at async LazyCachingMode.getRootCACrlFromPCS (/opt/intel/sgx-dcap-pccs/services/caching_modes/cachingMode.js:145:12)
    at async Proxy.getRootCaCrl (/opt/intel/sgx-dcap-pccs/services/rootcacrlService.js:47:11)
    at async getRootCaCrl (/opt/intel/sgx-dcap-pccs/controllers/rootcacrlController.js:38:21)
2022-03-10 08:43:14.189 [info]: 127.0.0.1 - - [10/Mar/2022:00:43:14 +0000] "GET /sgx/certification/v3/rootcacrl HTTP/1.1" 502 57 "-" "curl/7.68.0"
```

**Comment by lingyuj** [comment]
Can you post your pccs config file? (default.json)

**Comment by deliciousdish** [comment]
```
{
    "HTTPS_PORT" : 8081,
    "hosts" : "127.0.0.1",
    "uri": "https://api.trustedservices.intel.com/sgx/certification/v3/",
    "ApiKey" : "7ab72860c8424093a26375f84751****",
    "proxy" : "http://[username]:[password]@proxy.****.com:8080",
    "RefreshSchedule": "0 0 1 * * *",
    "UserTokenHash" : "",
    "AdminTokenHash" : "",
    "CachingFillMode" : "LAZY",
    "LogLevel" : "debug",
    "DB_CONFIG" : "sqlite",
    "sqlite" : {
        "database" : "database",
        "username" : "username",
        "password" : "password",
        "options" : {
            "host": "localhost",
            "dialect": "sqlite",
            "pool": {
                "max": 5,
                "min": 0,
                "acquire": 30000,
                "idle": 10000
            },
            "define": {
                "freezeTableName": true
            },
            "logging" : false,
            "storage": "pckcache.db"
        }
    },
    "mysql" : {
        "database" : "pckcache",
        "username" : "root",
        "password" : "mypass",
        "options" : {
            "host": "localhost",
            "dialect": "mysql",
            "pool": {
                "max": 5,
                "min": 0,
                "acquire": 30000,
                "idle": 10000
            },
            "define": {
                "freezeTableName": true
            },
            "logging" : false
        }
    }
}

```

**Comment by deliciousdish** [comment]
I think the root cause is when pccs connect to proxy, it receives a self signed cerficate and terminate the connection. So, how to set the pccs do not check the proxy certificate, just like curl -k?

**Comment by deliciousdish** [comment]
add
```
process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = 0; 
```
in /opt/intel/sgx-dcap-pccs/pcs_client/pcs_client.js and problem is solved.

**Comment by andyzyb** [comment]
Nice finding.  Probably need an option in pccs configuration file to handle such situation.

**Comment by TY-cc** [comment]
> add
> 
> ```
> process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = 0; 
> ```
> 
> in /opt/intel/sgx-dcap-pccs/pcs_client/pcs_client.js and problem is solved.

Hi, I have same problem. And use this don't have resolve, even my pccs not work.  Do you have some suggestions?

**Comment by deliciousdish** [comment]
Try to set process.env in the function do_request.

**Comment by TY-cc** [comment]
> Try to set process.env in the function do_request.

I try it.，but no effect. Thanks.
Another problem that PCCS’ log report error:  "tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80"
I don't use proxy. This is why?

**Comment by TY-cc** [comment]
> Try to set process.env in the function do_request.

I try it.，but no effect. Thanks.
Another problem that PCCS’ log report error:  "tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80"
I don't use proxy. This is why?

**Comment by lingyuj** [comment]
> > Try to set process.env in the function do_request.
> 
> I try it.，but no effect. Thanks. Another problem that PCCS’ log report error: "tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80" I don't use proxy. This is why?

Yes, this is what confuses me. Since PCCS can be setup on any machine, can you try a different one?

**Comment by TY-cc** [comment]
OK. I will try a different machine. Current server processor is Intel ( R ) Xeon ( R ) E-2378 CPU @ 2.60GHz. Tomorrow I 'll try to use a server with a processor of 4314

> > > Try to set process.env in the function do_request.
> > 
> > 
> > I try it.，but no effect. Thanks. Another problem that PCCS’ log report error: "tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80" I don't use proxy. This is why?
> 
> Yes, this is what confuses me. Since PCCS can be setup on any machine, can you try a different one?
