### ISSUE TITLE
Quote Generation Error in sgx_qe_get_target_info. 0xe00b

### ISSUE THREAD

**Issue by vbedida79** [intel/SGXDataCenterAttestationPrimitives#228]
Hi, 

On openshift container platform cluster 4.10 (with RHCOS worker nodes) I run PCCS service as pod with local network true according to [pccs dockerfile](https://github.com/intel/SGXDataCenterAttestationPrimitives/tree/master/QuoteGeneration/pccs/container). I follow  [aesmd pod](https://github.com/intel/intel-device-plugins-for-kubernetes/blob/main/deployments/sgx_aesmd/base/intel-sgx-aesmd.yaml)  and [aesmd quote generation example](https://github.com/intel/intel-device-plugins-for-kubernetes/tree/main/deployments/sgx_enclave_apps/overlays/sgx_ecdsa_aesmd_quote )  .
The PCCS service subscription API key is in default_config.json. (followed [this](https://www.intel.com/content/www/us/en/developer/articles/guide/intel-software-guard-extensions-data-center-attestation-primitives-quick-install-guide.html))
Aesmd and pccs pod run correctly. But when quote generation example container runs, it gives error:
`Step1: Call sgx_qe_get_target_info:Error in sgx_qe_get_target_info. 0xe00b`

Also PCCS container logs has error , with  GET /sgx/certification/v3/pckcert? showing error 404 
```
`2022-05-02 21:08:49.745 [info]: Client Request-ID : f3514016fba546129056674c6225424e
2022-05-02 21:08:50.055 [info]: Request-ID is : 55cba5795d244bc7a8cac64c5b451c4e
2022-05-02 21:08:50.055 [error]: Error: No cache data for this platform.
    at Proxy.getPckCertFromPCS (/opt/intel/pccs/services/logic/commonCacheLogic.js:86:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async LazyCachingMode.getPckCertFromPCS (/opt/intel/pccs/services/caching_modes/cachingMode.js:126:12)
    at async Proxy.getPckCert (/opt/intel/pccs/services/pckcertService.js:115:16)
    at async getPckCert (/opt/intel/pccs/controllers/pckcertController.js:77:25)
```

Could you please help figure out what might be missing, thanks.

**Comment by jsun39** [comment]
what is your platform type that used to generate Quote? If it is one multi-package platform(like ICX-SP platform), would you please double check whether the platform has been registered？

**Comment by vbedida79** [comment]
I use RHCOS Linux Kernel 4.18.0-305.40.1 Ice Lake server. Could you please tell what registration service to use for this server?

**Comment by jsun39** [comment]
Ice Lake Server is one multi-package platform, you need do registration firstly. Please install the multi-package agent in your host:  I guess you have already setup your local repo for SGX, you can just execute some command like the following to install it:
sudo yum install sgx-ra-service

**Comment by vbedida79** [comment]
understood thank yo, will check that. Meanwhile, since its a multi package platform, https://sbx.api.portal.trustedservices.intel.com/ do I have to subscribe to SBX Intel® Provisioning Certification Service and use that generated API key, instead of the general Provisioning Certification Service? Could that be reason for error as well?

**Comment by vbedida79** [comment]
Hi, we have RHCOS server on OCP 4.10 and it has limited permissions to run services on hosts. Could I please know if its possible to run the sgx-ra-sample as a privileged container on the SGX node? any other way you suggest to install this service, thanks.
