### ISSUE TITLE
Failed to start pccs.service due to error: "throw er; // Unhandled 'error' event"

### ISSUE THREAD

**Issue by gyohuangxin** [intel/SGXDataCenterAttestationPrimitives#263]
I setup the PCCS services following https://www.intel.com/content/www/us/en/developer/articles/guide/intel-software-guard-extensions-data-center-attestation-primitives-quick-install-guide.html, but it failed and its error logs are below:
```
$ journalctl -u pccs -f
Sep 30 16:24:04 sgx02 systemd[1]: Started Provisioning Certificate Caching Service (PCCS).
Sep 30 16:24:05 sgx02 node[1339839]: Fri, 30 Sep 2022 08:24:05 GMT morgan deprecated default format: use combined format at node_modules/esm/esm.js:1:278827
Sep 30 16:24:06 sgx02 node[1339839]: 2022-09-30 16:24:06.799 [info]: DB Migration (Ver.2 -> 3) -- Start
Sep 30 16:24:06 sgx02 node[1339839]: 2022-09-30 16:24:06.807 [error]: Validation error
Sep 30 16:24:06 sgx02 node[1339839]: events.js:377
Sep 30 16:24:06 sgx02 node[1339839]:       throw er; // Unhandled 'error' event
Sep 30 16:24:06 sgx02 node[1339839]:       ^
Sep 30 16:24:06 sgx02 node[1339839]: NodeError: write after end
Sep 30 16:24:06 sgx02 node[1339839]:     at writeAfterEnd (/opt/intel/sgx-dcap-pccs/node_modules/readable-stream/lib/_stream_writable.js:261:12)
Sep 30 16:24:06 sgx02 node[1339839]:     at DerivedLogger.Writable.write (/opt/intel/sgx-dcap-pccs/node_modules/readable-stream/lib/_stream_writable.js:305:21)
Sep 30 16:24:06 sgx02 node[1339839]:     at DerivedLogger.<computed> [as error] (/opt/intel/sgx-dcap-pccs/node_modules/winston/lib/winston/create-logger.js:81:14)
Sep 30 16:24:06 sgx02 node[1339839]:     at process.<anonymous> (/opt/intel/sgx-dcap-pccs/pccs_server.js:55:10)
Sep 30 16:24:06 sgx02 node[1339839]:     at process.emit (events.js:412:35)
Sep 30 16:24:06 sgx02 node[1339839]:     at process.emit (domain.js:475:12)
Sep 30 16:24:06 sgx02 node[1339839]:     at process.<anonymous> (internal/process/execution.js:167:25)
Sep 30 16:24:06 sgx02 node[1339839]:     at process.<anonymous> (/opt/intel/sgx-dcap-pccs/node_modules/esm/esm.js:1:289374)
Sep 30 16:24:06 sgx02 node[1339839]:     at process.<anonymous> (/opt/intel/sgx-dcap-pccs/node_modules/esm/esm.js:1:289220)
Sep 30 16:24:06 sgx02 node[1339839]:     at process.<anonymous> (/opt/intel/sgx-dcap-pccs/node_modules/esm/esm.js:1:284879)
Sep 30 16:24:06 sgx02 node[1339839]:     at Object.apply (/opt/intel/sgx-dcap-pccs/node_modules/esm/esm.js:1:199341)
Sep 30 16:24:06 sgx02 node[1339839]: Emitted 'error' event on DerivedLogger instance at:
Sep 30 16:24:06 sgx02 node[1339839]:     at errorOrDestroy (/opt/intel/sgx-dcap-pccs/node_modules/readable-stream/lib/internal/streams/destroy.js:98:101)
Sep 30 16:24:06 sgx02 node[1339839]:     at writeAfterEnd (/opt/intel/sgx-dcap-pccs/node_modules/readable-stream/lib/_stream_writable.js:263:3)
Sep 30 16:24:06 sgx02 node[1339839]:     at DerivedLogger.Writable.write (/opt/intel/sgx-dcap-pccs/node_modules/readable-stream/lib/_stream_writable.js:305:21)
Sep 30 16:24:06 sgx02 node[1339839]:     [... lines matching original stack trace ...]
Sep 30 16:24:06 sgx02 node[1339839]:     at Object.apply (/opt/intel/sgx-dcap-pccs/node_modules/esm/esm.js:1:199341)
Sep 30 16:24:06 sgx02 systemd[1]: pccs.service: Main process exited, code=exited, status=7/NOTRUNNING
Sep 30 16:24:06 sgx02 systemd[1]: pccs.service: Failed with result 'exit-code'.
```

The dependencies version:
```
$ sudo dpkg -l|grep sgx
ii  libsgx-ae-epid                        2.17.100.3-focal1                 amd64        Intel(R) Software Guard Extensions QE and PvE
ii  libsgx-ae-id-enclave                  1.14.100.3-focal1                 amd64        Intel(R) Software Guard Extensions Data Center Attestation Primitives ID enclave
ii  libsgx-ae-le                          2.17.101.1-focal1                 amd64        Intel(R) Software Guard Extensions LE
ii  libsgx-ae-pce                         2.17.100.3-focal1                 amd64        Intel(R) Software Guard Extensions PCE
ii  libsgx-ae-qe3                         1.14.100.3-focal1                 amd64        Intel(R) Software Guard Extensions QE3
ii  libsgx-ae-qve                         1.14.100.3-focal1                 amd64        Intel(R) Software Guard Extensions QVE
ii  libsgx-aesm-ecdsa-plugin              2.17.100.3-focal1                 amd64        ECDSA Quote Plugin for Intel(R) Software Guard Extensions AESM Service
ii  libsgx-aesm-epid-plugin               2.17.100.3-focal1                 amd64        EPID Quote Plugin for Intel(R) Software Guard Extensions AESM Service
ii  libsgx-aesm-launch-plugin             2.17.101.1-focal1                 amd64        Launch Plugin for Intel(R) Software Guard Extensions AESM Service
ii  libsgx-aesm-pce-plugin                2.17.100.3-focal1                 amd64        PCE Plugin for Intel(R) Software Guard Extensions AESM Service
ii  libsgx-aesm-quote-ex-plugin           2.17.100.3-focal1                 amd64        Unified Quote Plugin for Intel(R) Software Guard Extensions AESM Service
ii  libsgx-dcap-default-qpl               1.14.100.3-focal1                 amd64        Intel(R) Software Guard Extensions Default Quote Provider Library
ii  libsgx-dcap-default-qpl-dbgsym        1.14.100.3-focal1                 amd64        debug symbols for libsgx-dcap-default-qpl
ii  libsgx-dcap-default-qpl-dev           1.14.100.3-focal1                 amd64        Intel(R) Software Guard Extensions Default Quote Provider Library For Developers
ii  libsgx-dcap-ql                        1.14.100.3-focal1                 amd64        Intel(R) Software Guard Extensions Data Center Attestation Primitives
ii  libsgx-dcap-ql-dbgsym                 1.14.100.3-focal1                 amd64        debug symbols for libsgx-dcap-ql
ii  libsgx-dcap-ql-dev                    1.14.100.3-focal1                 amd64        Intel(R) Software Guard Extensions Data Center Attestation Primitives For Developers
ii  libsgx-dcap-quote-verify              1.14.100.3-focal1                 amd64        Intel(R) Software Guard Extensions Data Center Attestation Primitives
ii  libsgx-enclave-common                 2.17.101.1-focal1                 amd64        Intel(R) Software Guard Extensions Enclave Common Loader
ii  libsgx-enclave-common-dev             2.17.101.1-focal1                 amd64        Intel(R) Software Guard Extensions Enclave Common Loader for Developers
ii  libsgx-epid                           2.17.100.3-focal1                 amd64        Intel(R) Software Guard Extensions EPID Quote Service
ii  libsgx-epid-dev                       2.17.100.3-focal1                 amd64        Intel(R) Software Guard Extensions EPID Quote Service for Developers
ii  libsgx-headers                        2.17.101.1-focal1                 amd64        Intel(R) Software Guard Extensions Basic Headers for Developers
ii  libsgx-launch                         2.17.101.1-focal1                 amd64        Intel(R) Software Guard Extensions Launch Service
ii  libsgx-launch-dev                     2.17.101.1-focal1                 amd64        Intel(R) Software Guard Extensions Launch Service for Developers
ii  libsgx-pce-logic                      1.14.100.3-focal1                 amd64        Intel(R) Software Guard Extensions Data Center Attestation Primitives
ii  libsgx-qe3-logic                      1.14.100.3-focal1                 amd64        Intel(R) Software Guard Extensions Data Center Attestation Primitives
ii  libsgx-quote-ex                       2.17.100.3-focal1                 amd64        Intel(R) Software Guard Extensions Unified Quote Service
ii  libsgx-quote-ex-dev                   2.17.100.3-focal1                 amd64        Intel(R) Software Guard Extensions Unified Quote Service for Developers
ii  libsgx-ra-network                     1.14.100.3-focal1                 amd64        Intel(R) Software Guard Extensions Registration Agent network library
ii  libsgx-ra-uefi                        1.14.100.3-focal1                 amd64        Intel(R) Software Guard Extensions Registration Agent UEFI library
ii  libsgx-uae-service                    2.17.100.3-focal1                 amd64        Intel(R) Software Guard Extensions Untrusted AE Service
ii  libsgx-urts                           2.17.101.1-focal1                 amd64        Intel(R) Software Guard Extensions uRTS
ii  sgx-aesm-service                      2.17.101.1-focal1                 amd64        Intel(R) Software Guard Extensions AESM Service
ii  sgx-dcap-pccs                         1.14.100.3-focal1                 amd64        Intel(R) Software Guard Extensions PCK Caching Service
ii  sgx-pck-id-retrieval-tool             1.14.100.3-focal1                 amd64        Intel(R) Software Guard Extensions: this tool is used to collect the platform information to retrieve the PCK certs from PCS(Provisioning Certification Server)
ii  sgx-ra-service                        1.14.100.3-focal1                 amd64        Intel(R) Software Guard Extensions Multi-Package Registration Agent Service
```

Thanks to anyone who can help.

**Comment by jsun39** [comment]
it seems that it fail during database migration.  Where does your older database coming from?

**Comment by gyohuangxin** [comment]
@jsun39 Thanks for your reply, we use this machine to develop applications with SGX. Then I tried to updated the pccs from 1.12 to 1.14 (other dependencies from 2.15 to 2.17), where may the older database came from. Is there any way to fix this?

**Comment by lingyuj** [comment]
If you are using sqlite, you can just backup the pckcache.db in the pccs folder and delete it, then restart PCCS to see what happers. BTW, what's your nodejs version?
