### ISSUE TITLE
QuoteGenerationSample run failed in sgx_qe_get_target_info.

### ISSUE THREAD

**Issue by Rlyown** [intel/SGXDataCenterAttestationPrimitives#270]
My CPU is `Intel(R) Xeon(R) Silver 4314 CPU`. And my platform only has this one CPU.

This is the error message from the sample.
```
sgx_qe_set_enclave_load_policy is valid in in-proc mode only and it is optional: the default enclave load policy is persistent:
set the enclave load policy as persistent:succeed!

Step1: Call sgx_qe_get_target_info:[get_platform_quote_cert_data ../qe_logic.cpp:378] Error returned from the p_sgx_get_quote_config API. 0xe011
Error in sgx_qe_get_target_info. 0xe011
```

And `pccs` log
```
Nov 16 00:22:00 localhost.localdomain node[1917934]: 2022-11-16 00:22:00.284 [info]: Client Request-ID : 5684c57d5dbe4abc8500a0fd3a43347c
Nov 16 00:22:01 localhost.localdomain node[1917934]: 2022-11-16 00:22:01.586 [info]: Request-ID is : af745fad7d93405f93ab57b697a83ac0
Nov 16 00:22:01 localhost.localdomain node[1917934]: 2022-11-16 00:22:01.587 [error]: Intel PCS server returns error(404).
Nov 16 00:22:01 localhost.localdomain node[1917934]: 2022-11-16 00:22:01.587 [error]: Intel PCS server returns error. Error code : 404
Nov 16 00:22:01 localhost.localdomain node[1917934]: 2022-11-16 00:22:01.588 [error]: Error: No cache data for this platform.
Nov 16 00:22:01 localhost.localdomain node[1917934]:     at Proxy.getPckCertFromPCS (/opt/intel/sgx-dcap-pccs/services/logic/commonCacheLogic.js:92:11)
Nov 16 00:22:01 localhost.localdomain node[1917934]:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
Nov 16 00:22:01 localhost.localdomain node[1917934]:     at async LazyCachingMode.getPckCertFromPCS (/opt/intel/sgx-dcap-pccs/services/caching_modes/cachingMode.js:126:12)
Nov 16 00:22:01 localhost.localdomain node[1917934]:     at async Proxy.getPckCert (/opt/intel/sgx-dcap-pccs/services/pckcertService.js:115:16)
Nov 16 00:22:01 localhost.localdomain node[1917934]:     at async getPckCert (/opt/intel/sgx-dcap-pccs/controllers/pckcertController.js:77:25)
Nov 16 00:22:01 localhost.localdomain node[1917934]: 2022-11-16 00:22:01.591 [info]: 127.0.0.1 - - [15/Nov/2022:16:22:01 +0000] "GET /sgx/certification/v3/pckcert?qeid=1CB8552E2F4854D1CED4ABCE8DAEB5D3&encrypted_ppid=D198C3DB91DFE01260D51719F8474ECB710D0353C34D5EBBA75C7C8101D77CB8BA94912269D2D55621AFA2F21C9913336A41DB492513B514A18FD9329B6AC294665DE8A55337CEAAC3DC82406F449FBC230E39B012EF584A3F3BF9350BD5F519C7BABE8FFBA217C51BDA70E7D024EDA061CB0DDA218D9A400BA27E1467F0CD4EF7E1C24E96C076B9928E0A11CE82AE4BC4AB05B71E06B663286574587BFF0EF57EB0B193A404E37F7D0F65A86DBC5AD8FBE0171658FEB454D31B114380E09CF9BA5853C340915F58E8E4DCE152123CF84F58CE11C199484ACFB7F140B67D7B5D9DFC5F471E104B763BC548AA03D5CD2933F7C97FE6BB823D4E615752C4C6FA3A0E7AA7B8C7F0FC88BA3D4D1AF90F2C07FF4A6412207A355F011B696E45AE443A4BCA823DD75922FDDE62AB12A9C56E91F96A30C764DC7C249FE4DFC7B33A6AC76F6FA7AA0D7B626FD475A75EDC7E392F31D3985392D62C9FCAF3210AA99A316B23B4A348BF9FF1D0962E3088858281EF537D5D0C2BDAF3D786A6FC71A1632E31&cpusvn=06060E0CFFFF00000000000000000000&pcesvn=0D00&pceid=0000 HTTP/1.1" 404 32 "-" "-"
```

How could I fix this problem.

**Comment by jdbeaney** [comment]
Did you 'register' your platform?  If not, you will need to perform either direct registration or indirect registration.

**Comment by Rlyown** [comment]
I have run `PCKIDRetrievalTool` before. Does this mean 'register'?

**Comment by jdbeaney** [comment]
Did the PCKIDRetrievalTool send the platform information to the PCCS (including the PlatformManifest)?

**Comment by Rlyown** [comment]
Sorry, I find what is causing this error. I misconfigured the `PCCS_URL` in PCKIDRetrievalTool.
I set it the same as in `/etc/sgx_default_qcnl.conf`.

It works now. Thanks!
