### ISSUE TITLE
ERROR:sgx_qe_get_target_info. 0xe011

### ISSUE THREAD

**Issue by b-garbacz** [intel/SGXDataCenterAttestationPrimitives#276]
Hey,
I installed Intel SGX SDK, PCCS and AESM by following "Installation guide for linux". I want to test it  by using QuoteGenerationSample but there is an error:
1.
```
./app
Step1: Call sgx_qe_get_target_info:Error in sgx_qe_get_target_info. 0xe011
```
2.
```
xxx@xxx~/SGXDataCenterAttestationPrimitives/SampleCode/QuoteGenerationSample$ sudo ./app
sgx_qe_set_enclave_load_policy is valid in in-proc mode only and it is optional: the default enclave load policy is persistent:
set the enclave load policy as persistent:succeed!

Step1: Call sgx_qe_get_target_info:[get_platform_quote_cert_data ../qe_logic.cpp:378] Error returned from the p_sgx_get_quote_config API. 0xe011
Error in sgx_qe_get_target_info. 0xe011
xxx@xxx:~/SGXDataCenterAttestationPrimitives/SampleCode/QuoteGenerationSample$



```

pccs log 
```
2022-12-15 14:53:24.682 [info]: Client Request-ID : 95437a1b774246dea63dd43017337465
2022-12-15 14:53:24.801 [info]: Request-ID is : d22b7bf4cd1b4a139b64a94930ca07ab
2022-12-15 14:53:24.801 [error]: Intel PCS server returns error(404).
2022-12-15 14:53:24.801 [error]: Intel PCS server returns error. Error code : 404
2022-12-15 14:53:24.802 [error]: Error: No cache data for this platform.
    at Module.getPckCertFromPCS (file:///opt/intel/sgx-dcap-pccs/services/logic/commonCacheLogic.js:92:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async LazyCachingMode.getPckCertFromPCS (file:///opt/intel/sgx-dcap-pccs/services/caching_modes/cachingMode.js:126:12)
    at async Module.getPckCert (file:///opt/intel/sgx-dcap-pccs/services/pckcertService.js:115:16)
    at async getPckCert (file:///opt/intel/sgx-dcap-pccs/controllers/pckcertController.js:77:25)
2022-12-15 14:53:24.808 [info]: 127.0.0.1 - - [15/Dec/2022:14:53:24 +0000] "GET /sgx/certification/v4/pckcert?qeid=xxxxxxx
```

This is  my config file default.json

(I registered my PCS)
```
{
    "HTTPS_PORT" : 8081,
    "hosts" : "0.0.0.0",
    "uri": "https://api.trustedservices.intel.com/sgx/certification/v4/",
    "ApiKey" : "xxxxxxxxxxxxxxxxx",
    "proxy" : "",
    "RefreshSchedule": "0 0 1 * * *",
    "UserTokenHash" : "d779d2b844709b5b3c38209cb8d70c8034c10bf71bd98de79471e7967609de7d9d6495236b7fc4aecad21e2aaf9f0639d0c44a5ae3443ea4ccb976793efc5c67",
    "AdminTokenHash" : "4e097495b61debdf948da0ecabded8b7020a88d1afdcb8228e009ce122f8a6ea1a46cd9e94f184461996de557d0581d045fe360b36db40dc216b95c6a4d41c77",
    "CachingFillMode" : "LAZY",
    "LogLevel" : "info",
    "DB_CONFIG" : "sqlite",
    "sqlite" : {
        "database" : "database",
        "username" : "username",
        "password" : "password",
        "options" : {
            "host": "localhost",
            "dialect": "sqlite",
            "pool": {
                "max": 5,
                "min": 0,
                "acquire": 30000,
                "idle": 10000
            },
            "define": {
                "freezeTableName": true
            },
            "logging" : false,
            "storage": "pckcache.db"
        }
    },
    "mysql" : {
        "database" : "pckcache",
        "username" : "root",
        "password" : "mypass",
        "options" : {
            "host": "localhost",
            "dialect": "mysql",
            "pool": {
                "max": 5,
                "min": 0,
                "acquire": 30000,
                "idle": 10000
            },
            "define": {
                "freezeTableName": true
            },
            "logging" : false
        }
    }
}
```

/etc/sgx_default_qcnl.conf
```
  //PCCS server address
  "pccs_url": "https://localhost:8081/sgx/certification/v4/",

  // To accept insecure HTTPS certificate, set this option to false
  "use_secure_cert": false,

```
After that I reseted pccs

I use In-kernel Driver
```
 uname -r
5.15.0-1029-azure
```
I have no idea how to fix it... I've checked similar issues before but none of them helped me

**Comment by dashuaic** [comment]
It seems you met similar issue like https://github.com/intel/SGXDataCenterAttestationPrimitives/issues/270
Can you 'register' your platform? you will need to perform either direct registration or indirect registration.

**Comment by b-garbacz** [comment]
@dashuaic 
Excuse me... What it does mean to 'register' my platform directly or indirectly? I registered my platform:
![image](https://user-images.githubusercontent.com/45511879/208059809-707fadd0-784e-4c93-b4ca-85e7c115d728.png)

**Comment by dashuaic** [comment]
For register, you can refer https://download.01.org/intel-sgx/latest/dcap-latest/linux/docs/Intel_SGX_DCAP_Multipackage_SW.pdf
2.4.1. Direct Registration
2.4.2. Indirect Registration

**Comment by jsun39** [comment]
@b-garbacz , Have your issue been resolved?
