### ISSUE TITLE
Cannot find jni_dcap_quoteverify in JavaQuoteVerificationSample when using mvn test

### ISSUE THREAD

**Issue by qiyuangong** [intel/SGXDataCenterAttestationPrimitives#290]
```bash
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.intel.sgx.SgxDcapQuoteVerifyTest
java.lang.UnsatisfiedLinkError: no jni_dcap_quoteverify in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at com.intel.sgx.SgxDcapVerifyQuoteJNI.<clinit>(SgxDcapVerifyQuoteJNI.java:107)
        at com.intel.sgx.SgxDcapQuoteVerifyTest.testsgxQvSetPath(SgxDcapQuoteVerifyTest.java:61)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

This lib is in `src/main/c/lib`.  It cannot be found when using `mvn test`.

**Comment by dashuaic** [comment]
Need to set the environment variable LD_LIBRARY_PATH to include the src/main/c/lib

Update environment variables

   $ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${Project_basedir}/src/main/c/lib

**Comment by qiyuangong** [comment]
> Need to set the environment variable LD_LIBRARY_PATH to include the src/main/c/lib
> 
> https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/4a1656b1c5baf2366898a9dc44d77483aac6fe1e/SampleCode/JavaQuoteVerificationSample/README.md?plain=1#L29
> 
> 
> Update environment variables
> $ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${Project_basedir}/src/main/c/lib

Yes. After adding this env. It works. :)

Issue closed.

The only problem is that. We always need to copy & add this lib into LD_LIBRARY_PATH, especially when we are trying to deploy on another server.
