### ISSUE TITLE
Can't build QuoteGeneration Library

### ISSUE THREAD

**Issue by gyohuangxin** [intel/SGXDataCenterAttestationPrimitives#309]
When I tried to build QuoteGeneration Library following https://github.com/intel/SGXDataCenterAttestationPrimitives/tree/master/QuoteGeneration#build-the-intelr-sgx-dcap-quote-generation-library-and-the-intelr-sgx-default-quote-provider-library-package, it failed with following errors:
```
root@a4bf0192c489:~/huangxin/SGXDataCenterAttestationPrimitives/QuoteGeneration# make
make -C pce_wrapper/linux
make[1]: Entering directory '/root/huangxin/SGXDataCenterAttestationPrimitives/QuoteGeneration/pce_wrapper/linux'
cc -Wjump-misses-init -Wstrict-prototypes -Wunsuffixed-float-constants -fstack-protector-strong -O2 -D_FORTIFY_SOURCE=2 -UDEBUG -DNDEBUG -ffunction-sections -fdata-sections -Wall -Wextra -Winit-self -Wpointer-arith -Wreturn-type -Waddress -Wsequence-point -Wformat-security -Wmissing-include-dirs -Wfloat-equal -Wundef -Wshadow -Wcast-align -Wconversion -Wredundant-decls -DITT_ARCH_IA64  -fcf-protection -fPIC -Werror -g  -I. -I../inc -I/opt/intel/sgxsdk/include -I../../common/inc/internal -I../../common/inc/internal/linux -I../../ae/common -I../../ae/inc -I../../ae/inc/internal -Werror -fPIC -c pce_u.c -o pce_u.o
cc -Wjump-misses-init -Wstrict-prototypes -Wunsuffixed-float-constants -fstack-protector-strong -O2 -D_FORTIFY_SOURCE=2 -UDEBUG -DNDEBUG -ffunction-sections -fdata-sections -Wall -Wextra -Winit-self -Wpointer-arith -Wreturn-type -Waddress -Wsequence-point -Wformat-security -Wmissing-include-dirs -Wfloat-equal -Wundef -Wshadow -Wcast-align -Wconversion -Wredundant-decls -DITT_ARCH_IA64  -fcf-protection -fPIC -Werror -g  -I. -I../inc -I/opt/intel/sgxsdk/include -I../../common/inc/internal -I../../common/inc/internal/linux -I../../ae/common -I../../ae/inc -I../../ae/inc/internal -Werror -fPIC -c ../../common/src/se_trace.c -o se_trace.o
cc -Wjump-misses-init -Wstrict-prototypes -Wunsuffixed-float-constants -fstack-protector-strong -O2 -D_FORTIFY_SOURCE=2 -UDEBUG -DNDEBUG -ffunction-sections -fdata-sections -Wall -Wextra -Winit-self -Wpointer-arith -Wreturn-type -Waddress -Wsequence-point -Wformat-security -Wmissing-include-dirs -Wfloat-equal -Wundef -Wshadow -Wcast-align -Wconversion -Wredundant-decls -DITT_ARCH_IA64  -fcf-protection -fPIC -Werror -g  -I. -I../inc -I/opt/intel/sgxsdk/include -I../../common/inc/internal -I../../common/inc/internal/linux -I../../ae/common -I../../ae/inc -I../../ae/inc/internal -Werror -fPIC -c ../../common/src/se_thread.c -o se_thread.o
g++ -Wnon-virtual-dtor -std=c++14 -fstack-protector-strong -O2 -D_FORTIFY_SOURCE=2 -UDEBUG -DNDEBUG -ffunction-sections -fdata-sections -Wall -Wextra -Winit-self -Wpointer-arith -Wreturn-type -Waddress -Wsequence-point -Wformat-security -Wmissing-include-dirs -Wfloat-equal -Wundef -Wshadow -Wcast-align -Wconversion -Wredundant-decls -DITT_ARCH_IA64  -fcf-protection -fPIC -Werror -g  -I. -I../inc -I/opt/intel/sgxsdk/include -I../../common/inc/internal -I../../common/inc/internal/linux -I../../ae/common -I../../ae/inc -I../../ae/inc/internal -c ../pce_wrapper.cpp -o pce_wrapper.o
g++ -Wnon-virtual-dtor -std=c++14 -fstack-protector-strong -O2 -D_FORTIFY_SOURCE=2 -UDEBUG -DNDEBUG -ffunction-sections -fdata-sections -Wall -Wextra -Winit-self -Wpointer-arith -Wreturn-type -Waddress -Wsequence-point -Wformat-security -Wmissing-include-dirs -Wfloat-equal -Wundef -Wshadow -Wcast-align -Wconversion -Wredundant-decls -DITT_ARCH_IA64  -fcf-protection -fPIC -Werror -g pce_u.o se_trace.o se_thread.o pce_wrapper.o -shared -pthread -Wl,-z,relro,-z,now,-z,noexecstack -Wl,--version-script=pce_wrapper.lds -Wl,--gc-sections -m64 -L../../build/linux -L/opt/intel/sgxsdk/lib64 -lsgx_urts -lpthread -ldl \
-Wl,-soname=libsgx_pce_logic.so.1 -o libsgx_pce_logic.so
ar rcsD libsgx_pce_logic.a pce_u.o se_trace.o se_thread.o pce_wrapper.o
make[1]: Leaving directory '/root/huangxin/SGXDataCenterAttestationPrimitives/QuoteGeneration/pce_wrapper/linux'
make -C quote_wrapper/tdx_quote/linux
make[1]: Entering directory '/root/huangxin/SGXDataCenterAttestationPrimitives/QuoteGeneration/quote_wrapper/tdx_quote/linux'
/opt/intel/sgxsdk/bin/x64/sgx_edger8r --untrusted ../enclave/tdqe.edl --search-path ../enclave
GEN  =>  tdqe_u.c
CC   <=  tdqe_u.c
/opt/intel/sgxsdk/bin/x64/sgx_edger8r --untrusted ../../quote/id_enclave/id_enclave.edl
GEN  =>  id_enclave_u.c
CC   <=  id_enclave_u.c
CC   <=  ../../../common/src/se_thread.c
CC   <=  ../../../common/src/se_trace.c
g++ -Wnon-virtual-dtor -std=c++14 -fstack-protector-strong -O2 -D_FORTIFY_SOURCE=2 -UDEBUG -DNDEBUG -ffunction-sections -fdata-sections -Wall -Wextra -Winit-self -Wpointer-arith -Wreturn-type -Waddress -Wsequence-point -Wformat-security -Wmissing-include-dirs -Wfloat-equal -Wundef -Wshadow -Wcast-align -Wconversion -Wredundant-decls -DITT_ARCH_IA64  -fcf-protection -g -MMD -fPIC -Wno-attributes -I/opt/intel/sgxsdk/include -I../inc -I../../common/inc -I./ -I../enclave -I../../../pce_wrapper/inc -I../../../common/inc/internal -I../../../common/inc/internal/linux -c ../td_ql_logic.cpp -o ../td_ql_logic.o
In file included from ../td_ql_logic.h:43,
                 from ../td_ql_logic.cpp:44:
../inc/td_ql_wrapper.h:166:46: error: ‘tee_att_att_key_id_t’ does not name a type; did you mean ‘sgx_ql_att_key_id_t’?
  166 | tee_att_error_t tee_att_create_context(const tee_att_att_key_id_t* p_att_key_id,
      |                                              ^~~~~~~~~~~~~~~~~~~~
      |                                              sgx_ql_att_key_id_t
../inc/td_ql_wrapper.h:340:5: error: ‘tee_att_att_key_id_t’ has not been declared
  340 |     tee_att_att_key_id_t* p_att_key_id);
      |     ^~~~~~~~~~~~~~~~~~~~
make[1]: *** [Makefile:102: ../td_ql_logic.o] Error 1
make[1]: Leaving directory '/root/huangxin/SGXDataCenterAttestationPrimitives/QuoteGeneration/quote_wrapper/tdx_quote/linux'
make: *** [Makefile:123: tdx_logic] Error 2
```

The version I tried is DCAP_1.16, the dependencies versions are:
```
root@a4bf0192c489:~/huangxin/SGXDataCenterAttestationPrimitives/QuoteGeneration# apt list --installed | grep libsgx

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libsgx-ae-epid/unknown,now 2.19.100.3-focal1 amd64 [installed]
libsgx-ae-id-enclave/unknown,now 1.16.100.2-focal1 amd64 [installed,automatic]
libsgx-ae-le/unknown,now 2.19.100.3-focal1 amd64 [installed]
libsgx-ae-pce/unknown,now 2.19.100.3-focal1 amd64 [installed]
libsgx-ae-qe3/unknown,now 1.16.100.2-focal1 amd64 [installed]
libsgx-ae-qve/unknown,now 1.16.100.2-focal1 amd64 [installed]
libsgx-aesm-ecdsa-plugin/unknown,now 2.19.100.3-focal1 amd64 [installed]
libsgx-aesm-epid-plugin/unknown,now 2.19.100.3-focal1 amd64 [installed]
libsgx-aesm-launch-plugin/unknown,now 2.19.100.3-focal1 amd64 [installed]
libsgx-aesm-pce-plugin/unknown,now 2.19.100.3-focal1 amd64 [installed]
libsgx-aesm-quote-ex-plugin/unknown,now 2.19.100.3-focal1 amd64 [installed]
libsgx-dcap-default-qpl-dev/unknown,now 1.16.100.2-focal1 amd64 [installed]
libsgx-dcap-default-qpl/unknown,now 1.16.100.2-focal1 amd64 [installed]
libsgx-dcap-ql-dev/unknown,now 1.16.100.2-focal1 amd64 [installed]
libsgx-dcap-ql/unknown,now 1.16.100.2-focal1 amd64 [installed]
libsgx-dcap-quote-verify-dev/unknown,now 1.16.100.2-focal1 amd64 [installed]
libsgx-dcap-quote-verify/unknown,now 1.16.100.2-focal1 amd64 [installed]
libsgx-enclave-common/unknown,now 2.19.100.3-focal1 amd64 [installed]
libsgx-epid-dev/unknown,now 2.19.100.3-focal1 amd64 [installed]
libsgx-epid/unknown,now 2.19.100.3-focal1 amd64 [installed]
libsgx-headers/unknown,now 2.19.100.3-focal1 amd64 [installed,automatic]
libsgx-launch-dev/unknown,now 2.19.100.3-focal1 amd64 [installed]
libsgx-launch/unknown,now 2.19.100.3-focal1 amd64 [installed]
libsgx-pce-logic/unknown,now 1.16.100.2-focal1 amd64 [installed,automatic]
libsgx-qe3-logic/unknown,now 1.16.100.2-focal1 amd64 [installed,automatic]
libsgx-quote-ex-dev/unknown,now 2.19.100.3-focal1 amd64 [installed]
libsgx-quote-ex/unknown,now 2.19.100.3-focal1 amd64 [installed]
libsgx-ra-network/unknown,now 1.16.100.2-focal1 amd64 [installed]
libsgx-ra-uefi/unknown,now 1.16.100.2-focal1 amd64 [installed]
libsgx-uae-service/unknown,now 2.19.100.3-focal1 amd64 [installed]
libsgx-urts/unknown,now 2.19.100.3-focal1 amd64 [installed]
```

**Comment by gyohuangxin** [comment]
@jsun39 We're using sgx_linux_x64_sdk_2.17.100.3.bin

**Comment by jsun39** [comment]
please update your sdk and source code to the latest version.  There should be one mismatch between your sdk and source code.

**Comment by fqiu1** [comment]
It's not related to SDK. you need to `libsgx-tdx-logic-dev`

**Comment by gyohuangxin** [comment]
@fqiu1 After `apt install libsgx-tdx-logic-dev`, the same error still happens:
```
ogic.cpp -o ../td_ql_logic.o
In file included from ../td_ql_logic.h:43,
                 from ../td_ql_logic.cpp:44:
../inc/td_ql_wrapper.h:166:46: error: ‘tee_att_att_key_id_t’ does not name a type; did you mean ‘sgx_ql_att_key_id_t’?
  166 | tee_att_error_t tee_att_create_context(const tee_att_att_key_id_t* p_att_key_id,
      |                                              ^~~~~~~~~~~~~~~~~~~~
      |                                              sgx_ql_att_key_id_t
../inc/td_ql_wrapper.h:340:5: error: ‘tee_att_att_key_id_t’ has not been declared
  340 |     tee_att_att_key_id_t* p_att_key_id);
      |     ^~~~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:102: ../td_ql_logic.o] Error 1
make[2]: Leaving directory '/root/huangxin/SGXDataCenterAttestationPrimitives/QuoteGeneration/quote_wrapper/tdx_quote/linux'
make[1]: *** [Makefile:123: tdx_logic] Error 2
make[1]: Leaving directory '/root/huangxin/SGXDataCenterAttestationPrimitives/QuoteGeneration'
make: *** [Makefile:280: rebuild] Error 2
```

We just want to use SGX feature and don't need TDX related things, is there any way to skip them?

**Comment by fqiu1** [comment]
> It's not related to SDK. you need to `libsgx-tdx-logic-dev`

Just noticed you have td_ql_wrapper.h in place. Then Junli is right, you need to use the corresponding SDK version

**Comment by fqiu1** [comment]
> @fqiu1 After `apt install libsgx-tdx-logic-dev`, the same error still happens:
> 
> ```
> ogic.cpp -o ../td_ql_logic.o
> In file included from ../td_ql_logic.h:43,
>                  from ../td_ql_logic.cpp:44:
> ../inc/td_ql_wrapper.h:166:46: error: ‘tee_att_att_key_id_t’ does not name a type; did you mean ‘sgx_ql_att_key_id_t’?
>   166 | tee_att_error_t tee_att_create_context(const tee_att_att_key_id_t* p_att_key_id,
>       |                                              ^~~~~~~~~~~~~~~~~~~~
>       |                                              sgx_ql_att_key_id_t
> ../inc/td_ql_wrapper.h:340:5: error: ‘tee_att_att_key_id_t’ has not been declared
>   340 |     tee_att_att_key_id_t* p_att_key_id);
>       |     ^~~~~~~~~~~~~~~~~~~~
> make[2]: *** [Makefile:102: ../td_ql_logic.o] Error 1
> make[2]: Leaving directory '/root/huangxin/SGXDataCenterAttestationPrimitives/QuoteGeneration/quote_wrapper/tdx_quote/linux'
> make[1]: *** [Makefile:123: tdx_logic] Error 2
> make[1]: Leaving directory '/root/huangxin/SGXDataCenterAttestationPrimitives/QuoteGeneration'
> make: *** [Makefile:280: rebuild] Error 2
> ```
> 
> We just want to use SGX feature and don't need TDX related things, is there any way to skip them?

You can uninstall the old SDK, and install the corresponding [SDK ](https://download.01.org/intel-sgx/sgx-dcap/1.16/linux/distro/ubuntu20.04-server/sgx_linux_x64_sdk_2.19.100.3.bin) to pass the build. libsgx-tdx-logic-dev is not required to build DCAP itself. You don't need to skip anything.

**Comment by fqiu1** [comment]
You need to install `libsgx-dcap-ql` and `sgx-dcap-pccs`, and configure them according to the:
https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/master/QuoteGeneration/pccs/README.md
https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/master/QuoteGeneration/qpl/README.md

**Comment by gyohuangxin** [comment]
I installed `libsgx-dcap-ql` and `sgx-dcap-pccs` before, and went through the guide you provide for correct configuration. But the pccs has error `Error: The platform was not found in the cache.` when receiving requests:
```
root@a4bf0192c489:~/huangxin/SGXDataCenterAttestationPrimitives/SampleCode/QuoteGenerationSample# sudo systemctl status pccs
● pccs.service - Provisioning Certificate Caching Service (PCCS)
     Loaded: loaded (/lib/systemd/system/pccs.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2023-04-24 01:45:43 PDT; 1min 19s ago
       Docs: https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/master/QuoteGeneration/pccs/README.md
   Main PID: 79161 (node)
      Tasks: 11 (limit: 541289)
     Memory: 33.9M
     CGroup: /system.slice/pccs.service
             └─79161 /usr/bin/node /opt/intel/sgx-dcap-pccs/pccs_server.js

Apr 24 01:45:43 a4bf0192c489.jf.intel.com systemd[1]: Started Provisioning Certificate Caching Service (PCCS).
Apr 24 01:45:44 a4bf0192c489.jf.intel.com node[79161]: 2023-04-24 01:45:44.580 [info]: HTTPS Server is running on: https://localhost:8081
Apr 24 01:46:55 a4bf0192c489.jf.intel.com node[79161]: 2023-04-24 01:46:55.557 [info]: Client Request-ID : 687aa53200aa4fd4890bb7db6b8f7acf
Apr 24 01:46:55 a4bf0192c489.jf.intel.com node[79161]: 2023-04-24 01:46:55.569 [error]: Error: The platform was not found in the cache.
Apr 24 01:46:55 a4bf0192c489.jf.intel.com node[79161]:     at ReqCachingMode.getPckCertFromPCS (file:///opt/intel/sgx-dcap-pccs/services/caching_modes/cachingMode.js:72:11)
Apr 24 01:46:55 a4bf0192c489.jf.intel.com node[79161]:     at CachingModeManager.getPckCertFromPCS (file:///opt/intel/sgx-dcap-pccs/services/caching_modes/cachingModeManager.js:54:23)
Apr 24 01:46:55 a4bf0192c489.jf.intel.com node[79161]:     at Module.getPckCert (file:///opt/intel/sgx-dcap-pccs/services/pckcertService.js:115:41)
Apr 24 01:46:55 a4bf0192c489.jf.intel.com node[79161]:     at async getPckCert (file:///opt/intel/sgx-dcap-pccs/controllers/pckcertController.js:77:25)
Apr 24 01:46:55 a4bf0192c489.jf.intel.com node[79161]: 2023-04-24 01:46:55.574 [info]: 127.0.0.1 - - [24/Apr/2023:08:46:55 +0000] "GET /sgx/certification/v4/pckcert?qeid=DAF458C683E9CA2BEFCE6D722E67AF25&encrypted_ppid=546F5E24A2C06EE37C04972D77905921B64E8E18A421F36CA06158E24AC5C7DF921C417>
```

**Comment by gyohuangxin** [comment]
@fqiu1 I went through the registration process following https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/master/tools/SGXPlatformRegistration/README.md, the registration seems to be successful:
```
root@a4bf0192c489:~/huangxin/SGXDataCenterAttestationPrimitives/SampleCode/QuoteGenerationSample# systemctl status mpa_registration_tool.service
● mpa_registration_tool.service - Intel MPA Registration
     Loaded: loaded (/lib/systemd/system/mpa_registration_tool.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Mon 2023-04-24 05:11:41 PDT; 5min ago
    Process: 81123 ExecStart=/opt/intel/sgx-ra-service/mpa_registration (code=exited, status=0/SUCCESS)
   Main PID: 81123 (code=exited, status=0/SUCCESS)

Apr 24 05:11:41 a4bf0192c489.jf.intel.com systemd[1]: Started Intel MPA Registration.
Apr 24 05:11:41 a4bf0192c489.jf.intel.com systemd[1]: mpa_registration_tool.service: Succeeded.
```
But above errors still happen:
```
root@a4bf0192c489:~/huangxin/SGXDataCenterAttestationPrimitives/SampleCode/QuoteGenerationSample# ./app
sgx_qe_set_enclave_load_policy is valid in in-proc mode only and it is optional: the default enclave load policy is persistent:
set the enclave load policy as persistent:succeed!

Step1: Call sgx_qe_get_target_info:[get_platform_quote_cert_data ../qe_logic.cpp:378] Error returned from the p_sgx_get_quote_config API. 0xe047
Error in sgx_qe_get_target_info. 0xe047
```

```
root@a4bf0192c489:~/huangxin/SGXDataCenterAttestationPrimitives/SampleCode/QuoteGenerationSample# systemctl status pccs
● pccs.service - Provisioning Certificate Caching Service (PCCS)
     Loaded: loaded (/lib/systemd/system/pccs.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2023-04-24 05:09:10 PDT; 12min ago
       Docs: https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/master/QuoteGeneration/pccs/README.md
   Main PID: 81008 (node)
      Tasks: 11 (limit: 541289)
     Memory: 34.0M
     CGroup: /system.slice/pccs.service
             └─81008 /usr/bin/node /opt/intel/sgx-dcap-pccs/pccs_server.js

Apr 24 05:15:05 a4bf0192c489.jf.intel.com node[81008]:     at Module.getPckCert (file:///opt/intel/sgx-dcap-pccs/services/pckcertService.js:115:41)
Apr 24 05:15:05 a4bf0192c489.jf.intel.com node[81008]:     at async getPckCert (file:///opt/intel/sgx-dcap-pccs/controllers/pckcertController.js:77:25)
Apr 24 05:15:05 a4bf0192c489.jf.intel.com node[81008]: 2023-04-24 05:15:05.395 [info]: 127.0.0.1 - - [24/Apr/2023:12:15:05 +0000] "GET /sgx/certification/v4/pckcert?qeid=DAF458C683E9CA2BEFCE6D722E67AF25&encrypted_ppid=95A64B46065CD746AC0631445DCC860F>
Apr 24 05:21:39 a4bf0192c489.jf.intel.com node[81008]: 2023-04-24 05:21:39.015 [info]: Client Request-ID : 83acbfc5971c4728b99307273cf95d87
Apr 24 05:21:39 a4bf0192c489.jf.intel.com node[81008]: 2023-04-24 05:21:39.022 [error]: Error: The platform was not found in the cache.
Apr 24 05:21:39 a4bf0192c489.jf.intel.com node[81008]:     at ReqCachingMode.getPckCertFromPCS (file:///opt/intel/sgx-dcap-pccs/services/caching_modes/cachingMode.js:72:11)
Apr 24 05:21:39 a4bf0192c489.jf.intel.com node[81008]:     at CachingModeManager.getPckCertFromPCS (file:///opt/intel/sgx-dcap-pccs/services/caching_modes/cachingModeManager.js:54:23)
Apr 24 05:21:39 a4bf0192c489.jf.intel.com node[81008]:     at Module.getPckCert (file:///opt/intel/sgx-dcap-pccs/services/pckcertService.js:115:41)
Apr 24 05:21:39 a4bf0192c489.jf.intel.com node[81008]:     at async getPckCert (file:///opt/intel/sgx-dcap-pccs/controllers/pckcertController.js:77:25)
Apr 24 05:21:39 a4bf0192c489.jf.intel.com node[81008]: 2023-04-24 05:21:39.026 [info]: 127.0.0.1 - - [24/Apr/2023:12:21:39 +0000] "GET /sgx/certification/v4/pckcert?qeid=DAF458C683E9CA2BEFCE6D722E67AF25&encrypted_ppid=1DA0B5A76A4BFB8B3048919A46CE22DF>
```

**Comment by fqiu1** [comment]
please paste the content of /var/log/mpa_registration.log

**Comment by gyohuangxin** [comment]
Seems no useful information in  /var/log/mpa_registration.log:
```
[24-04-2023 05:04:16] INFO: SGX Registration Agent version: 1.16.100.2
[24-04-2023 05:04:16] INFO: Starts Registration Agent Flow.
[24-04-2023 05:04:16] INFO: Registration Flow - Registration status indicates registration is completed successfully. MPA has nothing to do.
[24-04-2023 05:04:16] INFO: Finished Registration Agent Flow.
[24-04-2023 05:06:22] INFO: SGX Registration Agent version: 1.16.100.2
[24-04-2023 05:06:22] INFO: Starts Registration Agent Flow.
[24-04-2023 05:06:22] INFO: Registration Flow - Registration status indicates registration is completed successfully. MPA has nothing to do.
[24-04-2023 05:06:22] INFO: Finished Registration Agent Flow.
[24-04-2023 05:09:53] INFO: SGX Registration Agent version: 1.16.100.2
[24-04-2023 05:09:53] INFO: Starts Registration Agent Flow.
[24-04-2023 05:09:53] INFO: Registration Flow - Registration status indicates registration is completed successfully. MPA has nothing to do.
[24-04-2023 05:09:53] INFO: Finished Registration Agent Flow.
[24-04-2023 05:11:41] INFO: SGX Registration Agent version: 1.16.100.2
[24-04-2023 05:11:41] INFO: Starts Registration Agent Flow.
[24-04-2023 05:11:41] INFO: Registration Flow - Registration status indicates registration is completed successfully. MPA has nothing to do.
[24-04-2023 05:11:41] INFO: Finished Registration Agent Flow.
```

**Comment by fqiu1** [comment]
Would you please set sgx factory reset in the bios and try the registration again?

**Comment by gyohuangxin** [comment]
OK, I will try. Thanks for your great help.

**Comment by gyohuangxin** [comment]
@fqiu1 I reset the SGX factory reset and tried the registration process, but the `0xe047` error still happens. Am I missing some steps?
There is one error in /var/log/mpa_registration.log:
```
[24-04-2023 08:04:21] INFO: Starts Registration Agent Flow.
[24-04-2023 08:04:21] INFO: SGX MP Server configuration flag indicates that Registration Server won't save encrypted platform keys.
[24-04-2023 08:04:21] INFO: Platform registration request (PLATFORM_MANIFEST) won't be send to Registration Server.
[24-04-2023 08:04:21] INFO: Please use management tool or PCKCertIDRetrievalTool to read PLATFORM_MANIFEST.
[24-04-2023 08:04:21] INFO: Finished Registration Agent Flow.
```
And the output of 
```
root@a4bf0192c489:~/huangxin/SGXDataCenterAttestationPrimitives/SampleCode/QuoteGenerationSample# PCKIDRetrievalTool

Intel(R) Software Guard Extensions PCK Cert ID Retrieval Tool Version 1.16.100.2

Error: unexpected error occurred while sending data to cache server.
Registration status has been set to completed status.
pckid_retrieval.csv has been generated successfully, however the data couldn't be sent to cache server!
```

**Comment by fqiu1** [comment]
Please double-check PCKCertIDRetrievalTool‘s config, and also check the PCCS log for detail.

**Comment by gyohuangxin** [comment]
It succussed after changing subscription key to "Product Intel® Software Guard Extensions Provisioning Certification Service subscription (1)" one:
```
root@a4bf0192c489:~# PCKIDRetrievalTool

Intel(R) Software Guard Extensions PCK Cert ID Retrieval Tool Version 1.16.100.2

Registration status has been set to completed status.
the data has been sent to cache server successfully and pckid_retrieval.csv has been generated successfully!
root@a4bf0192c489:~# vim /opt/intel/sgx-pck-id-retrieval-tool/network_setting.conf
root@a4bf0192c489:~# systemctl status pccs
● pccs.service - Provisioning Certificate Caching Service (PCCS)
     Loaded: loaded (/lib/systemd/system/pccs.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2023-04-24 23:57:07 PDT; 58s ago
       Docs: https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/master/QuoteGeneration/pccs/README.md
   Main PID: 5791 (node)
      Tasks: 11 (limit: 541289)
     Memory: 37.1M
     CGroup: /system.slice/pccs.service
             └─5791 /usr/bin/node /opt/intel/sgx-dcap-pccs/pccs_server.js

Apr 24 23:57:07 a4bf0192c489.jf.intel.com systemd[1]: Started Provisioning Certificate Caching Service (PCCS).
Apr 24 23:57:08 a4bf0192c489.jf.intel.com node[5791]: 2023-04-24 23:57:08.426 [info]: HTTPS Server is running on: https://localhost:8081
Apr 24 23:57:49 a4bf0192c489.jf.intel.com node[5791]: 2023-04-24 23:57:49.175 [info]: Client Request-ID : 325a699e16aa4aa9a174513b101d6fa1
Apr 24 23:57:50 a4bf0192c489.jf.intel.com node[5791]: 2023-04-24 23:57:50.122 [info]: Request-ID is : e32820a691b5420096674a075058be55
Apr 24 23:57:50 a4bf0192c489.jf.intel.com node[5791]: 2023-04-24 23:57:50.463 [info]: Request-ID is : d805da808ca7477ea8009b3eaf3735e6
Apr 24 23:57:50 a4bf0192c489.jf.intel.com node[5791]: 2023-04-24 23:57:50.819 [info]: Request-ID is : 17093260ca3047bbac4db5937a8cd649
Apr 24 23:57:51 a4bf0192c489.jf.intel.com node[5791]: 2023-04-24 23:57:51.247 [info]: Request-ID is : eada70802124422f8252153d7bcbe247
Apr 24 23:57:51 a4bf0192c489.jf.intel.com node[5791]: 2023-04-24 23:57:51.624 [info]: Request-ID is : 06eef9e6c79244b88fd994f0fdaa0ada
Apr 24 23:57:51 a4bf0192c489.jf.intel.com node[5791]: 2023-04-24 23:57:51.664 [info]: 127.0.0.1 - - [25/Apr/2023:06:57:51 +0000] "POST /sgx/certification/v4/platforms HTTP/1.1" 200 21 "-" "-"

```

I think we can close this issue, @fqiu1 @jsun39 thanks for your great help!

**Comment by coolcoolcoo** [comment]
It succussed after changing subscription key to "Product Intel® Software Guard Extensions Provisioning Certification Service subscription (1)" one:  Can you tell us exactly how it works?
