### ISSUE TITLE
pccs not work in EMR ubuntu22.04

### ISSUE THREAD

**Issue by qiming-007** [intel/SGXDataCenterAttestationPrimitives#321]
HW: EMR
OS: ubuntu 22.04
Kernel: 5.19.0

Errors for `PCKIDRetrievalTool`:

```
root@emrcselocal:~/qiming# PCKIDRetrievalTool

Intel(R) Software Guard Extensions PCK Cert ID Retrieval Tool Version 1.16.100.2

Error: unexpected error occurred while sending data to cache server.
Registration status has been set to completed status.
pckid_retrieval.csv has been generated successfully, however the data couldn't be sent to cache server!
```

Error log from `pccs_server.log`:
```
2023-06-28 05:44:09.202 [info]: DB Migration (Ver.0 -> 1) -- Start
2023-06-28 05:44:09.208 [info]: DB Migration -- Done.
2023-06-28 05:44:09.237 [info]: DB Migration (Ver.1 -> 2) -- Start
2023-06-28 05:44:09.248 [info]: DB Migration -- Done.
2023-06-28 05:44:09.277 [info]: DB Migration (Ver.2 -> 3) -- Start
2023-06-28 05:44:09.284 [info]: DB Migration -- Done.
2023-06-28 05:44:09.327 [info]: HTTPS Server is running on: https://localhost:8081
2023-06-28 05:48:22.194 [info]: Client Request-ID : ad479850fbbc4c17b0f04492ae1e278b
2023-06-28 05:48:24.179 [info]: Request-ID is : 0420480203c64b9d97324e805b2a7395
2023-06-28 05:48:24.179 [error]: Intel PCS server returns error(400).
2023-06-28 05:48:24.179 [error]: Intel PCS server returns error. Error code : 400
2023-06-28 05:48:24.179 [error]: Error: No cache data for this platform.
    at Module.getPckCertFromPCS (file:///opt/intel/sgx-dcap-pccs/services/logic/commonCacheLogic.js:92:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ReqCachingMode.registerPlatforms (file:///opt/intel/sgx-dcap-pccs/services/caching_modes/cachingMode.js:205:7)
    at async Module.registerPlatforms (file:///opt/intel/sgx-dcap-pccs/services/platformsRegService.js:107:3)
    at async postPlatforms (file:///opt/intel/sgx-dcap-pccs/controllers/platformsController.js:40:5)
2023-06-28 05:48:24.181 [info]: 127.0.0.1 - - [28/Jun/2023:05:48:24 +0000] "POST /sgx/certification/v4/platforms HTTP/1.1" 404 32 "-" "-"
```

sgx libs version
```
root@emrcselocal:~/qiming# dpkg -l |grep sgx
ii  libsgx-ae-epid                                    2.19.100.3-jammy1                       amd64        Intel(R) Software Guard Extensions QE and PvE
ii  libsgx-ae-id-enclave                              1.16.100.2-jammy1                       amd64        Intel(R) Software Guard Extensions Data Center Attestation Primitives ID enclave
ii  libsgx-ae-le                                      2.19.100.3-jammy1                       amd64        Intel(R) Software Guard Extensions LE
ii  libsgx-ae-pce                                     2.19.100.3-jammy1                       amd64        Intel(R) Software Guard Extensions PCE
ii  libsgx-ae-qe3                                     1.16.100.2-jammy1                       amd64        Intel(R) Software Guard Extensions QE3
ii  libsgx-ae-qve                                     1.16.100.2-jammy1                       amd64        Intel(R) Software Guard Extensions QVE
ii  libsgx-aesm-ecdsa-plugin                          2.19.100.3-jammy1                       amd64        ECDSA Quote Plugin for Intel(R) Software Guard Extensions AESM Service
ii  libsgx-aesm-epid-plugin                           2.19.100.3-jammy1                       amd64        EPID Quote Plugin for Intel(R) Software Guard Extensions AESM Service
ii  libsgx-aesm-launch-plugin                         2.19.100.3-jammy1                       amd64        Launch Plugin for Intel(R) Software Guard Extensions AESM Service
ii  libsgx-aesm-pce-plugin                            2.19.100.3-jammy1                       amd64        PCE Plugin for Intel(R) Software Guard Extensions AESM Service
ii  libsgx-aesm-quote-ex-plugin                       2.19.100.3-jammy1                       amd64        Unified Quote Plugin for Intel(R) Software Guard Extensions AESM Service
ii  libsgx-dcap-default-qpl                           1.16.100.2-jammy1                       amd64        Intel(R) Software Guard Extensions Default Quote Provider Library
ii  libsgx-dcap-default-qpl-dev                       1.16.100.2-jammy1                       amd64        Intel(R) Software Guard Extensions Default Quote Provider Library For Developers
ii  libsgx-dcap-ql                                    1.16.100.2-jammy1                       amd64        Intel(R) Software Guard Extensions Data Center Attestation Primitives
ii  libsgx-dcap-ql-dev                                1.16.100.2-jammy1                       amd64        Intel(R) Software Guard Extensions Data Center Attestation Primitives For Developers
ii  libsgx-dcap-quote-verify                          1.16.100.2-jammy1                       amd64        Intel(R) Software Guard Extensions Data Center Attestation Primitives
ii  libsgx-enclave-common                             2.19.100.3-jammy1                       amd64        Intel(R) Software Guard Extensions Enclave Common Loader
ii  libsgx-enclave-common-dev                         2.19.100.3-jammy1                       amd64        Intel(R) Software Guard Extensions Enclave Common Loader for Developers
ii  libsgx-epid                                       2.19.100.3-jammy1                       amd64        Intel(R) Software Guard Extensions EPID Quote Service
ii  libsgx-epid-dev                                   2.19.100.3-jammy1                       amd64        Intel(R) Software Guard Extensions EPID Quote Service for Developers
ii  libsgx-headers                                    2.19.100.3-jammy1                       amd64        Intel(R) Software Guard Extensions Basic Headers for Developers
ii  libsgx-launch                                     2.19.100.3-jammy1                       amd64        Intel(R) Software Guard Extensions Launch Service
ii  libsgx-launch-dev                                 2.19.100.3-jammy1                       amd64        Intel(R) Software Guard Extensions Launch Service for Developers
ii  libsgx-pce-logic                                  1.16.100.2-jammy1                       amd64        Intel(R) Software Guard Extensions Data Center Attestation Primitives
ii  libsgx-qe3-logic                                  1.16.100.2-jammy1                       amd64        Intel(R) Software Guard Extensions Data Center Attestation Primitives
ii  libsgx-quote-ex                                   2.19.100.3-jammy1                       amd64        Intel(R) Software Guard Extensions Unified Quote Service
ii  libsgx-quote-ex-dev                               2.19.100.3-jammy1                       amd64        Intel(R) Software Guard Extensions Unified Quote Service for Developers
ii  libsgx-ra-uefi                                    1.16.100.2-jammy1                       amd64        Intel(R) Software Guard Extensions Registration Agent UEFI library
ii  libsgx-uae-service                                2.19.100.3-jammy1                       amd64        Intel(R) Software Guard Extensions Untrusted AE Service
ii  libsgx-urts                                       2.19.100.3-jammy1                       amd64        Intel(R) Software Guard Extensions uRTS
ii  sgx-aesm-service                                  2.19.100.3-jammy1                       amd64        Intel(R) Software Guard Extensions AESM Service
ii  sgx-dcap-pccs                                     1.16.100.2-jammy1                       amd64        Intel(R) Software Guard Extensions PCK Caching Service
ii  sgx-pck-id-retrieval-tool                         1.16.100.2-jammy1                       amd64        Intel(R) Software Guard Extensions: this tool is used to collect the plat
```
Configuration for `pccs`:
```
{
    "HTTPS_PORT" : 8081,
    "hosts" : "0.0.0.0",
    "uri": "https://api.trustedservices.intel.com/sgx/certification/v4/",
    "ApiKey" : "******",
    "proxy" : "*****",
    "RefreshSchedule": "0 0 1 * * *",
    "UserTokenHash" : "****",
    "AdminTokenHash" : "***",
    "CachingFillMode" : "REQ",
    "LogLevel" : "info",
    "DB_CONFIG" : "sqlite",
    "sqlite" : {
        "database" : "database",
        "username" : "username",
        "password" : "password",
        "options" : {
            "host": "localhost",
            "dialect": "sqlite",
            "pool": {
                "max": 5,
                "min": 0,
                "acquire": 30000,
                "idle": 10000
            },
            "define": {
                "freezeTableName": true
            },
            "logging" : false,
            "storage": "pckcache.db"
        }
```

Any help is appreciated.

**Comment by lingyuj** [comment]
Is your platform a pre-production platform? If so, you shouldn't use api.trustedservices.intel.com

**Comment by qiming-007** [comment]
> Is your platform a pre-production platform? If so, you shouldn't use api.trustedservices.intel.com. You can try sbx.api.trustedservices.intel.com

Modify to `sbx.api.trustedservices.intel.com` cannot work neither after rebooting pccs service.
Checked `pccs_server.log`:

```
2023-06-28 06:57:02.987 [error]: The server address used by the caching db is different from the one in the configuration file.
2023-06-28 06:57:18.647 [error]: The server address used by the caching db is different from the one in the configuration file.
2023-06-28 06:57:34.152 [error]: The server address used by the caching db is different from the one in the configuration file.
2023-06-28 06:57:49.656 [error]: The server address used by the caching db is different from the one in the configuration file.
2023-06-28 06:58:05.151 [error]: The server address used by the caching db is different from the one in the configuration file.
2023-06-28 06:58:20.638 [error]: The server address used by the caching db is different from the one in the configuration file.
```
How to solve this error?

**Comment by lingyuj** [comment]
> pckcache.db

Delete the pckcache.db file and restart pccs.

**Comment by qiming-007** [comment]
New errors:
```
2023-06-28 07:26:08.771 [info]: DB Migration (Ver.0 -> 1) -- Start
2023-06-28 07:26:08.778 [info]: DB Migration -- Done.
2023-06-28 07:26:08.799 [info]: DB Migration (Ver.1 -> 2) -- Start
2023-06-28 07:26:08.810 [info]: DB Migration -- Done.
2023-06-28 07:26:08.830 [info]: DB Migration (Ver.2 -> 3) -- Start
2023-06-28 07:26:08.839 [info]: DB Migration -- Done.
2023-06-28 07:26:08.873 [info]: HTTPS Server is running on: https://localhost:8081
2023-06-28 07:26:25.299 [info]: Client Request-ID : 673a8b55b49a45f583873fb39ae29f6c
2023-06-28 07:26:26.806 [info]: Request-ID is : undefined
2023-06-28 07:26:26.806 [error]: Intel PCS server returns error(401).{ "statusCode": 401, "message": "Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription." }
2023-06-28 07:26:26.807 [error]: Intel PCS server returns error. Error code : 401
2023-06-28 07:26:26.807 [error]: Error: No cache data for this platform.
    at Module.getPckCertFromPCS (file:///opt/intel/sgx-dcap-pccs/services/logic/commonCacheLogic.js:92:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ReqCachingMode.registerPlatforms (file:///opt/intel/sgx-dcap-pccs/services/caching_modes/cachingMode.js:205:7)
    at async Module.registerPlatforms (file:///opt/intel/sgx-dcap-pccs/services/platformsRegService.js:107:3)
    at async postPlatforms (file:///opt/intel/sgx-dcap-pccs/controllers/platformsController.js:40:5)
2023-06-28 07:26:26.809 [info]: 127.0.0.1 - - [28/Jun/2023:07:26:26 +0000] "POST /sgx/certification/v4/platforms HTTP/1.1" 404 32 "-" "-"
```
Need a new subscription key?

**Comment by lingyuj** [comment]
> Deleted `pckcache.db` and got new errors:
> 
> ```
> 2023-06-28 07:26:08.771 [info]: DB Migration (Ver.0 -> 1) -- Start
> 2023-06-28 07:26:08.778 [info]: DB Migration -- Done.
> 2023-06-28 07:26:08.799 [info]: DB Migration (Ver.1 -> 2) -- Start
> 2023-06-28 07:26:08.810 [info]: DB Migration -- Done.
> 2023-06-28 07:26:08.830 [info]: DB Migration (Ver.2 -> 3) -- Start
> 2023-06-28 07:26:08.839 [info]: DB Migration -- Done.
> 2023-06-28 07:26:08.873 [info]: HTTPS Server is running on: https://localhost:8081
> 2023-06-28 07:26:25.299 [info]: Client Request-ID : 673a8b55b49a45f583873fb39ae29f6c
> 2023-06-28 07:26:26.806 [info]: Request-ID is : undefined
> 2023-06-28 07:26:26.806 [error]: Intel PCS server returns error(401).{ "statusCode": 401, "message": "Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription." }
> 2023-06-28 07:26:26.807 [error]: Intel PCS server returns error. Error code : 401
> 2023-06-28 07:26:26.807 [error]: Error: No cache data for this platform.
>     at Module.getPckCertFromPCS (file:///opt/intel/sgx-dcap-pccs/services/logic/commonCacheLogic.js:92:11)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async ReqCachingMode.registerPlatforms (file:///opt/intel/sgx-dcap-pccs/services/caching_modes/cachingMode.js:205:7)
>     at async Module.registerPlatforms (file:///opt/intel/sgx-dcap-pccs/services/platformsRegService.js:107:3)
>     at async postPlatforms (file:///opt/intel/sgx-dcap-pccs/controllers/platformsController.js:40:5)
> 2023-06-28 07:26:26.809 [info]: 127.0.0.1 - - [28/Jun/2023:07:26:26 +0000] "POST /sgx/certification/v4/platforms HTTP/1.1" 404 32 "-" "-"
> ```
> 
> Need a new subscription key?

Yeah, you need the API key for sbx server.

**Comment by qiming-007** [comment]
Thanks a lot, worked after subscription a new key from [https://sbx.api.portal.trustedservices.intel.com/](https://sbx.api.portal.trustedservices.intel.com/)
