### ISSUE TITLE
Latest release points to https://github.com/intel/SGXDataCenterAttestationPrimitives/releases/tag/DCAP_1.19

### ISSUE THREAD

**Issue by nmwael** [intel/SGXDataCenterAttestationPrimitives#357]
However if I try to build QVS there are failing tests. (./SGXDataCenterAttestationPrimitives/QuoteVerification/QuoteVerificationService/build.sh)

If one should build against https://github.com/intel/SGXDataCenterAttestationPrimitives/releases/tag/dcap_1.19_reproducible 

Please make it clear that we need todo that.
[failingtests.txt](https://github.com/intel/SGXDataCenterAttestationPrimitives/files/13513130/failingtests.txt)

**Comment by nmwael** [comment]
[dcap_1.19_reproducible] fails because of:
#10 24.81   file COPY cannot find "/qvl/ThirdParty/hunter/openssl/hunter.cmake": No
#10 24.81   such file or directory.

**Comment by lzha101** [comment]
Hi @nmwael, thanks for reporting this. Suggest you switch to tag/**DCAP_1.19** instead of tag/**dcap_1.19_reproducible** for standard building DCAP. The reproducible tag  is only to reproduce the SGX prebuilt binaries, such as prebuilt AEs, prebuilt libraries, in a reproducible environment (docker + NIX). It is not target for normal build. But we will consider adding back the missing files in next reproducible branch.

**Comment by nmwael** [comment]
dcap_1.19 fails with 

`
#19 13.97   1) verify attestation evidence handler tests
#19 13.97        execute - SGX - UpToDate:
#19 13.97 
#19 13.97       AssertionError [ERR_ASSERTION]: 500 == 200
#19 13.97       + expected - actual
#19 13.97 
#19 13.97       -500
#19 13.97       +200
#19 13.97       
#19 13.97       at TestContext.assertPositive (handlers/verifyAttestationEvidenceTest.js:344:16)
#19 13.97       at TestContext.assertPositiveSgxStandard (handlers/verifyAttestationEvidenceTest.js:357:14)
#19 13.97       at Context.<anonymous> (handlers/verifyAttestationEvidenceTest.js:382:11)
#19 13.97 
#19 13.97   2) verify attestation evidence handler tests
#19 13.97        execute - SGX - ConfigurationNeeded:
#19 13.97 
#19 13.97       AssertionError [ERR_ASSERTION]: 500 == 200
#19 13.97       + expected - actual
#19 13.97 
#19 13.97       -500
#19 13.97       +200
#19 13.97       
#19 13.97       at TestContext.assertPositive (handlers/verifyAttestationEvidenceTest.js:344:16)
#19 13.97       at TestContext.assertPositiveSgxStandard (handlers/verifyAttestationEvidenceTest.js:357:14)
#19 13.97       at Context.<anonymous> (handlers/verifyAttestationEvidenceTest.js:410:11)
#19 13.97 
#19 13.97   3) verify attestation evidence handler tests
#19 13.97        execute - SGX - ConfigurationNeeded/TCB_OUT_OF_DATE:
#19 13.97 
#19 13.97       AssertionError [ERR_ASSERTION]: 500 == 200
#19 13.97       + expected - actual
#19 13.97 
#19 13.97       -500
#19 13.97       +200
#19 13.97       
#19 13.97       at TestContext.assertPositive (handlers/verifyAttestationEvidenceTest.js:344:16)
#19 13.97       at TestContext.assertPositiveSgxStandard (handlers/verifyAttestationEvidenceTest.js:357:14)
#19 13.97       at Context.<anonymous> (handlers/verifyAttestationEvidenceTest.js:443:11)
#19 13.97 
#19 13.97   4) verify attestation evidence handler tests
#19 13.97        execute - TDX - UpToDate:
#19 13.97 
#19 13.97       AssertionError [ERR_ASSERTION]: 500 == 200
#19 13.97       + expected - actual
#19 13.97 
#19 13.97       -500
#19 13.97       +200
#19 13.97       
#19 13.97       at TestContext.assertPositive (handlers/verifyAttestationEvidenceTest.js:344:16)
#19 13.97       at TestContext.assertPositiveTdx (handlers/verifyAttestationEvidenceTest.js:363:14)
#19 13.97       at Context.<anonymous> (handlers/verifyAttestationEvidenceTest.js:473:11)
#19 13.97 
#19 13.97   5) verify attestation evidence handler tests
#19 13.97        execute - TDX - ConfigurationNeeded:
#19 13.97 
#19 13.97       AssertionError [ERR_ASSERTION]: 500 == 200
#19 13.97       + expected - actual
#19 13.97 
#19 13.97       -500
#19 13.97       +200
#19 13.97       
#19 13.97       at TestContext.assertPositive (handlers/verifyAttestationEvidenceTest.js:344:16)
#19 13.97       at Context.<anonymous> (handlers/verifyAttestationEvidenceTest.js:500:11)
#19 13.97 
#19 13.97   6) verify attestation evidence handler tests
#19 13.97        execute - TDX - ConfigurationNeeded/TCB_OUT_OF_DATE:
#19 13.97 
#19 13.97       AssertionError [ERR_ASSERTION]: 500 == 200
#19 13.97       + expected - actual
#19 13.97 
#19 13.97       -500
#19 13.97       +200
#19 13.97       
#19 13.97       at TestContext.assertPositive (handlers/verifyAttestationEvidenceTest.js:344:16)
#19 13.97       at Context.<anonymous> (handlers/verifyAttestationEvidenceTest.js:536:11)
#19 13.97 
#19 13.97   7) verify attestation evidence handler tests
#19 13.97        execute - TDX - TCB level mismatch:
#19 13.97 
#19 13.97       AssertionError [ERR_ASSERTION]: 500 == 400
#19 13.97       + expected - actual
#19 13.97 
#19 13.97       -500
#19 13.97       +400
#19 13.97       
#19 13.97       at Context.<anonymous> (handlers/verifyAttestationEvidenceTest.js:570:16)
#19 13.97 
#19 13.97   8) verify attestation evidence handler tests
#19 13.97        execute - TDX - Enclave TCB level mismatch:
#19 13.97 
#19 13.97       AssertionError [ERR_ASSERTION]: 500 == 400
#19 13.97       + expected - actual
#19 13.97 
#19 13.97       -500
#19 13.97       +400
#19 13.97       
#19 13.97       at Context.<anonymous> (handlers/verifyAttestationEvidenceTest.js:607:16)
#19 13.97 
#19 13.97   9) verify attestation evidence handler tests
#19 13.97        execute - TDX - Enclave TCB level match between levels:
#19 13.97 
#19 13.97       AssertionError [ERR_ASSERTION]: 500 == 200
#19 13.97       + expected - actual
#19 13.97 
#19 13.97       -500
#19 13.97       +200
#19 13.97       
#19 13.97       at TestContext.assertPositive (handlers/verifyAttestationEvidenceTest.js:344:16)
#19 13.97       at TestContext.assertPositiveTdx (handlers/verifyAttestationEvidenceTest.js:363:14)
#19 13.97       at Context.<anonymous> (handlers/verifyAttestationEvidenceTest.js:639:11)
#19 13.97 
#19 13.97   10) verify attestation evidence handler tests
#19 13.97        execute - TDX - TCB level mismatch:
#19 13.97 
#19 13.97       AssertionError [ERR_ASSERTION]: 500 == 400
#19 13.97       + expected - actual
#19 13.97 
#19 13.97       -500
#19 13.97       +400
#19 13.97       
#19 13.97       at Context.<anonymous> (handlers/verifyAttestationEvidenceTest.js:711:16)
#19 13.97 
#19 13.98   11) verify attestation evidence handler tests
#19 13.98        execute - TDX - unexpected empty advisoryIDs:
#19 13.98 
#19 13.98       AssertionError [ERR_ASSERTION]: 500 == 200
#19 13.98       + expected - actual
#19 13.98 
#19 13.98       -500
#19 13.98       +200
#19 13.98       
#19 13.98       at TestContext.assertPositive (handlers/verifyAttestationEvidenceTest.js:344:16)
#19 13.98       at TestContext.assertPositiveTdx (handlers/verifyAttestationEvidenceTest.js:363:14)
#19 13.98       at Context.<anonymous> (handlers/verifyAttestationEvidenceTest.js:833:11)
#19 13.98 
#19 13.98   12) verify attestation evidence handler tests
#19 13.98        execute - qvl returns positive status results in status 200:
#19 13.98 
#19 13.98       AssertionError [ERR_ASSERTION]: Http statuses don't match for QVL status 0
#19 13.98       + expected - actual
#19 13.98 
#19 13.98       -500
#19 13.98       +200
#19 13.98       
#19 13.98       at testQvlStatus (handlers/verifyAttestationEvidenceTest.js:961:16)
#19 13.98       at async Context.<anonymous> (handlers/verifyAttestationEvidenceTest.js:974:13)
#19 13.98 
#19 13.98   13) verify attestation evidence handler tests
#19 13.98        execute - get CRL in DER format from distribution point:
#19 13.98 
#19 13.98       AssertionError [ERR_ASSERTION]: 500 == 200
#19 13.98       + expected - actual
#19 13.98 
#19 13.98       -500
#19 13.98       +200
#19 13.98       
#19 13.98       at TestContext.assertPositive (handlers/verifyAttestationEvidenceTest.js:344:16)
#19 13.98       at TestContext.assertPositiveSgxStandard (handlers/verifyAttestationEvidenceTest.js:357:14)
#19 13.98       at Context.<anonymous> (handlers/verifyAttestationEvidenceTest.js:1377:11)
#19 13.98 
#19 13.98   14) verify attestation evidence handler tests
#19 13.98        execute - tcb levels out of order:
#19 13.98 
#19 13.98       AssertionError [ERR_ASSERTION]: 500 == 200
#19 13.98       + expected - actual
#19 13.98 
#19 13.98       -500
#19 13.98       +200
#19 13.98       
#19 13.98       at TestContext.assertPositive (handlers/verifyAttestationEvidenceTest.js:344:16)
#19 13.98       at TestContext.assertPositiveSgxStandard (handlers/verifyAttestationEvidenceTest.js:357:14)
#19 13.98       at Context.<anonymous> (handlers/verifyAttestationEvidenceTest.js:1401:11)
#19 13.98 
#19 13.98   15) verify attestation evidence handler tests
#19 13.98        scalable sgx type:
#19 13.98 
#19 13.98       AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
#19 13.98 
#19 13.98 500 !== 200
#19 13.98 
#19 13.98       + expected - actual
#19 13.98 
#19 13.98       -500
#19 13.98       +200
#19 13.98       
#19 13.98       at Context.<anonymous> (handlers/verifyAttestationEvidenceTest.js:1419:16)
#19 13.98 
#19 13.98   16) verify attestation evidence handler tests
#19 13.98        scalable with integrity sgx type:
#19 13.98 
#19 13.98       AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
#19 13.98 
#19 13.98 500 !== 200
#19 13.98 
#19 13.98       + expected - actual
#19 13.98 
#19 13.98       -500
#19 13.98       +200
#19 13.98       
#19 13.98       at Context.<anonymous> (handlers/verifyAttestationEvidenceTest.js:1438:16)
#19 13.98 
#19 13.98   17) verify attestation evidence handler tests
#19 13.98        not supported sgx type:
#19 13.98 
#19 13.98       AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
#19 13.98 + actual - expected
#19 13.98 
#19 13.98 + 'Cannot convert 0x234,66,146,108,32,8,69,0,142,77,157,223,160,227,225,13 to a BigInt'
#19 13.98 - 'Unsupported sgxType'
#19 13.98       + expected - actual
#19 13.98 
#19 13.98       -Cannot convert 0x234,66,146,108,32,8,69,0,142,77,157,223,160,227,225,13 to a BigInt
#19 13.98       +Unsupported sgxType
#19 13.98       
#19 13.98       at Context.<anonymous> (handlers/verifyAttestationEvidenceTest.js:1458:16)
#19 13.98 
#19 13.98   18) verify attestation evidence handler tests
#19 13.98        sign verification report failure:
#19 13.98 
#19 13.98       AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
#19 13.98 + actual - expected
#19 13.98 
#19 13.98 + 'Cannot convert 0x211,8,162,239,150,153,70,207,129,70,67,95,121,74,224,91 to a BigInt'
#19 13.98 - 'Failed to sign the report. VCS returned status: 404'
#19 13.98       + expected - actual
#19 13.98 
#19 13.98       -Cannot convert 0x211,8,162,239,150,153,70,207,129,70,67,95,121,74,224,91 to a BigInt
#19 13.98       +Failed to sign the report. VCS returned status: 404
#19 13.98       
#19 13.98       at Context.<anonymous> (handlers/verifyAttestationEvidenceTest.js:1476:16)
#19 13.98 
#19 13.98   19) verify attestation evidence handler tests
#19 13.98        nonce
#19 13.98          not provided:
#19 13.98 
#19 13.98       AssertionError [ERR_ASSERTION]: 500 == 200
#19 13.98       + expected - actual
#19 13.98 
#19 13.98       -500
#19 13.98       +200
#19 13.98       
#19 13.98       at TestContext.assertPositive (handlers/verifyAttestationEvidenceTest.js:344:16)
#19 13.98       at TestContext.assertPositiveSgxStandard (handlers/verifyAttestationEvidenceTest.js:357:14)
#19 13.98       at Context.<anonymous> (handlers/verifyAttestationEvidenceTest.js:1033:15)
#19 13.98 
#19 13.98   20) verify attestation evidence handler tests
#19 13.98        configuration
#19 13.98          no flags - no configuration field:
#19 13.98 
#19 13.98       AssertionError [ERR_ASSERTION]: 500 == 200
#19 13.98       + expected - actual
#19 13.98 
#19 13.98       -500
#19 13.98       +200
#19 13.98       
#19 13.98       at TestContext.assertPositive (handlers/verifyAttestationEvidenceTest.js:344:16)
#19 13.98       at TestContext.assertPositiveSgxStandard (handlers/verifyAttestationEvidenceTest.js:357:14)
#19 13.98       at Context.<anonymous> (handlers/verifyAttestationEvidenceTest.js:1053:15)
#19 13.98 
#19 13.98   21) verify attestation evidence handler tests
#19 13.98        configuration
#19 13.98          dynamic platform:
#19 13.98 
#19 13.98       AssertionError [ERR_ASSERTION]: 500 == 200
#19 13.98       + expected - actual
#19 13.98 
#19 13.98       -500
#19 13.98       +200
#19 13.98       
#19 13.98       at TestContext.assertPositive (handlers/verifyAttestationEvidenceTest.js:344:16)
#19 13.98       at TestContext.assertPositiveSgxStandard (handlers/verifyAttestationEvidenceTest.js:357:14)
#19 13.98       at Context.<anonymous> (handlers/verifyAttestationEvidenceTest.js:1070:15)
#19 13.98 
#19 13.98   22) verify attestation evidence handler tests
#19 13.98        configuration
#19 13.98          cached keys:
#19 13.98 
#19 13.98       AssertionError [ERR_ASSERTION]: 500 == 200
#19 13.98       + expected - actual
#19 13.98 
#19 13.98       -500
#19 13.98       +200
#19 13.98       
#19 13.98       at TestContext.assertPositive (handlers/verifyAttestationEvidenceTest.js:344:16)
#19 13.98       at TestContext.assertPositiveSgxStandard (handlers/verifyAttestationEvidenceTest.js:357:14)
#19 13.98       at Context.<anonymous> (handlers/verifyAttestationEvidenceTest.js:1087:15)
#19 13.98 
#19 13.98   23) verify attestation evidence handler tests
#19 13.98        configuration
#19 13.98          SMT enabled:
#19 13.98 
#19 13.98       AssertionError [ERR_ASSERTION]: 500 == 200
#19 13.98       + expected - actual
#19 13.98 
#19 13.98       -500
#19 13.98       +200
#19 13.98       
#19 13.98       at TestContext.assertPositive (handlers/verifyAttestationEvidenceTest.js:344:16)
#19 13.98       at TestContext.assertPositiveSgxStandard (handlers/verifyAttestationEvidenceTest.js:357:14)
#19 13.98       at Context.<anonymous> (handlers/verifyAttestationEvidenceTest.js:1104:15)
#19 13.98 
#19 13.98   24) verify attestation evidence handler tests
#19 13.98        configuration
#19 13.98          multiple flags:
#19 13.98 
#19 13.98       AssertionError [ERR_ASSERTION]: 500 == 200
#19 13.98       + expected - actual
#19 13.98 
#19 13.98       -500
#19 13.98       +200
#19 13.98       
#19 13.98       at TestContext.assertPositive (handlers/verifyAttestationEvidenceTest.js:344:16)
#19 13.98       at TestContext.assertPositiveSgxStandard (handlers/verifyAttestationEvidenceTest.js:357:14)
#19 13.98       at Context.<anonymous> (handlers/verifyAttestationEvidenceTest.js:1125:15)
#19 13.98 
#19 13.98 
#19 13.98 
#19 ERROR: process "/bin/sh -c cd /qvs/test && npm install && NODE_ENV=production npm test" did not complete successfully: exit code: 24
------
 > [qvs-builder 10/10] RUN cd /qvs/test && npm install && NODE_ENV=production npm test:
13.98 
13.98       -500
13.98       +200
13.98       
13.98       at TestContext.assertPositive (handlers/verifyAttestationEvidenceTest.js:344:16)
13.98       at TestContext.assertPositiveSgxStandard (handlers/verifyAttestationEvidenceTest.js:357:14)
13.98       at Context.<anonymous> (handlers/verifyAttestationEvidenceTest.js:1125:15)
13.98 
13.98 
13.98 
------
Dockerfile:63
--------------------
  61 |     COPY test /qvs/test
  62 |     # test QVS
  63 | >>> RUN cd /qvs/test && npm install && NODE_ENV=production npm test
  64 |     
  65 |     FROM node:lts-slim
--------------------
ERROR: failed to solve: process "/bin/sh -c cd /qvs/test && npm install && NODE_ENV=production npm test" did not complete successfully: exit code: 24
Error when building Docker image
Error: Process completed with exit code 7.`

**Comment by bgotowal** [comment]
The Quote Verification Service (QVS) has been discontinued and is no longer part of the DCAP repository as a submodule. As a result, build issues related to QVS (including the failing tests reported here) will not be addressed. If you need quote verification functionality, please refer to the Quote Verification Library (QVL) that remains part of DCAP, or use the in-process sgx_qv_verify_quote API provided by the DCAP Quote Verification Library.
