### ISSUE TITLE
No cache data for this platform on VM

### ISSUE THREAD

**Issue by marioolf** [intel/SGXDataCenterAttestationPrimitives#360]
So I have a VM with Intel SGX on version 1.14 and 2.17 (I need those exact versions). When I try to run the PCKIDRetrievalTool for PCCS, I get the following:

```
Intel(R) Software Guard Extensions PCK Cert ID Retrieval Tool Version 1.14.100.3

Warning: platform manifest is not available or current platform is not multi-package platform.
Error: unexpected error happend during sending data to cache server.
pckid_retrieval.csv has been generated successfully, however the data couldn't be sent to cache server!
```

And on PCCS:

```
dic 26 10:22:22 teaclave-vm node[10841]: 2023-12-26 10:22:22.933 [info]: Request-ID is : 275bda7b9d314790a9bd65a038afc6c7
dic 26 10:22:22 teaclave-vm node[10841]: 2023-12-26 10:22:22.934 [error]: Intel PCS server returns error(404).
dic 26 10:22:22 teaclave-vm node[10841]: 2023-12-26 10:22:22.935 [error]: Intel PCS server returns error. Error code : 404
dic 26 10:22:22 teaclave-vm node[10841]: 2023-12-26 10:22:22.936 [error]: Error: No cache data for this platform.
dic 26 10:22:22 teaclave-vm node[10841]:     at Proxy.getPckCertFromPCS (/opt/intel/sgx-dcap-pccs/services/logic/commonCacheLogic.js:92:11)
dic 26 10:22:22 teaclave-vm node[10841]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
dic 26 10:22:22 teaclave-vm node[10841]:     at async ReqCachingMode.registerPlatforms (/opt/intel/sgx-dcap-pccs/services/caching_modes/cachingMode.js:205:7)
dic 26 10:22:22 teaclave-vm node[10841]:     at async Proxy.registerPlatforms (/opt/intel/sgx-dcap-pccs/services/platformsRegService.js:107:3)
dic 26 10:22:22 teaclave-vm node[10841]:     at async postPlatforms (/opt/intel/sgx-dcap-pccs/controllers/platformsController.js:40:5)
dic 26 10:22:22 teaclave-vm node[10841]: 2023-12-26 10:22:22.946 [info]: 127.0.0.1 - - [26/Dec/2023:10:22:22 +0000] "POST /sgx/certification/v3/platforms HTTP/1.1" 404 32 "-" "-"
```

The host machine also has pccs, on latest version, and works perfectly, also PCKDIRetrievalTool works as it should, but I need it to work on VM because of version issues.

I read that it could be because of BIOS issues, my VM is running the following BIOS, host BIOS is up to date:

```
BIOS Information
        Vendor: SeaBIOS
        Version: rel-1.16.2-0-gea1b7a073390-prebuilt.qemu.org
        Release Date: 04/01/2014
        Address: 0xE8000
        Runtime Size: 96 kB
        ROM Size: 64 kB
        Characteristics:
                BIOS characteristics not supported
                Targeted content distribution is supported
        BIOS Revision: 0.0
```

SampleCodes work perfectly on both VM and host machine, the only problem is the pccs thing.

**Comment by dashuaic** [comment]
Did you 'register' your platform? If not, you will need to perform either direct registration or indirect registration.

**Comment by marioolf** [comment]
Isn't running PCKIDRetrieval tool enough to register the platform?

**Comment by reclock** [comment]
@marioolf How did you solve it in the end

**Comment by jsun39** [comment]
depended on your environment configuration. If your pccs was in LAZY mode, and your PCKIDRetrieval tool has configured to connect with PCCS: Yes, running PCKIDRetrieval tool is enough to finish the registration.
