### ISSUE TITLE
No cache data for this platform and Error in sgx_qe_get_target_info. 0xe011

### ISSUE THREAD

**Issue by xiaoran33** [intel/SGXDataCenterAttestationPrimitives#365]
Hello, I currently have a physical server machine with an Intel (R) Xeon(R) Platinum 8352S * 2 CPU. The system is using Ubuntu 20.04,Currently, There is an issue with my PCCS service.
pccs status:
```
2024-01-23 10:23:55.848 [error]: Intel PCS server returns error(404).
2024-01-23 10:23:55.849 [error]: Intel PCS server returns error. Error code : 404
2024-01-23 10:23:55.849 [error]: Error: No cache data for this platform.
    at Module.getPckCertFromPCS (file:///opt/intel/sgx-dcap-pccs/services/logic/commonCacheLogic.js:92:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async LazyCachingMode.getPckCertFromPCS (file:///opt/intel/sgx-dcap-pccs/services/caching_modes/cachingMode.js:126:12)
    at async Module.getPckCert (file:///opt/intel/sgx-dcap-pccs/services/pckcertService.js:115:16)
    at async getPckCert (file:///opt/intel/sgx-dcap-pccs/controllers/pckcertController.js:77:25)
2024-01-23 10:23:55.851 [info]: 127.0.0.1 - - [23/Jan/2024:02:23:55 +0000] "GET /sgx/certification/v4/pckcert?qeid=90DB3BAD3A9CB27F04A33E1E4D88968A&encrypted_ppid=7AAC228FFE2E56B311A8DB880929B97A499A61A1BBA18AFABC7CE7CF573D1CDE6CB3D1ABA027AF49D6C9034E403C12F52F3DC4CEC187FDE8655E4C13A8E4A03B0DA2AFB8099F5F46F00DB984A2D929318F6DCB88F8B9029E71673144D2D8066B9A455E9D190095EDE87BE95CD680AAEE5DCE27D66BEA0CA0B1CF301DB9BD27E6BFDCBE73D3F7797F70EBF7C4AF6A224A5C73B52427D6351E2271695AD62D95AF10EC6CEBF972964039C5E96C1A57AAAFF240E4994D052A12BE8305A70CF2B71F97F9EE29BDB2BFDD3FF4A2CED5D4E79B81A8A9E1B56700A8419718A3267FC36612EE1567A1049E8176F93EE15EC4C6382255628EAC24D20C657C5AEE7ADF05967FD7F33FF4AD2EBB38834FD78A3B2AA78E7F20E905F1AD410D5B5E6215D4D6A5B9380F13984D1FAAE3AF860A35B22705304E64FA8678E3A2A33D891F44178CE646B50B4460917E6E011CA4162A5E954E16E360AEE390E4E14214A90D7F0724AED062C87844AB4299F2648DF45E63A0A0E04C88ADADFB564BEDA7EEEC3E9170AB&cpusvn=060D0E0DFFFF00000000000000000000&pcesvn=0F00&pceid=0000 HTTP/1.1" 404 32 "-" "-"
```
mpa status:
```
● mpa_registration_tool.service - Intel MPA Registration
     Loaded: loaded (/lib/systemd/system/mpa_registration_tool.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Mon 2024-01-22 13:39:00 CST; 1 day 1h ago
    Process: 7052 ExecStart=/opt/intel/sgx-ra-service/mpa_registration (code=exited, status=0/SUCCESS)
   Main PID: 7052 (code=exited, status=0/SUCCESS)

1月 22 13:38:59 huawei-2288H-V6 systemd[1]: Started Intel MPA Registration.
1月 22 13:39:00 huawei-2288H-V6 systemd[1]: mpa_registration_tool.service: Succeeded.
```
QuoteGenerationSample status:
```
root@2288H-V6:~/SGXDataCenterAttestationPrimitives/SampleCode/QuoteGenerationSample# ./app             
[APP] Info: sgx_qe_set_enclave_load_policy is valid in in-proc mode only and it is optional: the default enclave load policy is persistent
[APP] Info: set the enclave load policy as persistent
[APP] Step1: Call sgx_qe_get_target_info:
[QPL] Error: No certificate data for this platform.
[get_platform_quote_cert_data ../qe_logic.cpp:388] Error returned from the p_sgx_get_quote_config API. 0xe011
Error in sgx_qe_get_target_info. 0xe011
```
Any help is appreciated.

**Comment by jly77** [comment]
Maybe your platform is not a production platform? What's the uri setting in your PCCS config file? You can try using 
https://sbx.api.trustedservices.intel.com/sgx/certification/v4/
then restart PCCS service.

**Comment by jsun39** [comment]
would you please paste the log file： /var/log/mpa_registration.log？

**Comment by xiaoran33** [comment]
> https://sbx.api.trustedservices.intel.com/sgx/certification/v4/

Modify default.json to sbx.api.trustedservices.intel.com and I generated an API key for sbx server and delete the pckcache.db file and restart pccs.Still reporting errors：
```
2024-01-23 15:52:40.076 [error]: Intel PCS server returns error(404).
2024-01-23 15:52:40.077 [error]: Intel PCS server returns error. Error code : 404
2024-01-23 15:52:40.077 [error]: Error: No cache data for this platform.
    at Module.getPckCertFromPCS (file:///opt/intel/sgx-dcap-pccs/services/logic/commonCacheLogic.js:92:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async LazyCachingMode.getPckCertFromPCS (file:///opt/intel/sgx-dcap-pccs/services/caching_modes/cachingMode.js:126:12)
    at async Module.getPckCert (file:///opt/intel/sgx-dcap-pccs/services/pckcertService.js:115:16)
    at async getPckCert (file:///opt/intel/sgx-dcap-pccs/controllers/pckcertController.js:77:25)
2024-01-23 15:52:40.081 [info]: 127.0.0.1 - - [23/Jan/2024:07:52:40 +0000] "GET /sgx/certification/v4/pckcert?qeid=90DB3BAD3A9CB27F04A33E1E4D88968A&encrypted_ppid=5BE9C0AC3C67F9E5F3045B139D35E07CCE1EBEEBF5A526C482C90D4FEAB75342FCEA05C3134E782DFCD6AC9776967B996D629C1337C2A3A477B9D52E1FA224990A42817F2CCCC8571D8D7DE7260D5D9E5198AE38B5CFE53E3B89AD4136B8F0DA01F7CB7DE79B58DB6A161E898F6386BFBE75058ED679E3D69AEC7C1E09C7220533EFBD3ED94C5C748DCEC648C7E9DEBCA7CA2E9C937C217FBF8DA78160AD32552E7A7706E3A100EEDEC49E290A23761C1568B482DCF6EC6639930BE3DBE17D304C3EFBE99D8AB2ED8D0F95CEF08DF6D056B4AFC6D8B8C8FCE89A6CF65A5682EF606C6F00764E846DABCDAE05C3C93DDCF0771B4E6EEE733ECCD654C334464387E36F6002DBF5D640E5CDCD9628CF3636154A2C5939307ADD795526EC7F6DCE569340C2CAE1B4A1C332D59EA86D8630CCCF1D335BCF3D5A8A236728131E94DBB9F351FE537D25DDCAC1C6CED5DCD406DC60A86A8C8D971FE35FA7F4068B8CFD0572F1D0D6DD1EC9D982C718390F804F59F289A70FD98D064983C5318208EACA30&cpusvn=060D0E0DFFFF00000000000000000000&pcesvn=0F00&pceid=0000 HTTP/1.1" 404 32 "-" "-"
```

**Comment by xiaoran33** [comment]
> would you please paste the log file： /var/log/mpa_registration.log？

```
[19-01-2024 06:37:16] INFO: SGX Registration Agent version: 1.19.100.3
[19-01-2024 06:37:16] INFO: Starts Registration Agent Flow.
[19-01-2024 06:37:16] INFO: Registration Flow - Registration status indicates registration is completed successfully. MPA has nothing to do.
[19-01-2024 06:37:16] INFO: Finished Registration Agent Flow.
[19-01-2024 06:39:07] INFO: SGX Registration Agent version: 1.19.100.3
[19-01-2024 06:39:07] INFO: Starts Registration Agent Flow.
[19-01-2024 06:39:07] INFO: Registration Flow - Registration status indicates registration is completed successfully. MPA has nothing to do.
[19-01-2024 06:39:07] INFO: Finished Registration Agent Flow.
[21-01-2024 12:03:18] INFO: SGX Registration Agent version: 1.19.100.3
[21-01-2024 12:03:18] INFO: Starts Registration Agent Flow.
[21-01-2024 12:03:18] INFO: Registration Flow - Registration status indicates registration is completed successfully. MPA has nothing to do.
[21-01-2024 12:03:18] INFO: Finished Registration Agent Flow.
[22-01-2024 01:38:59] INFO: SGX Registration Agent version: 1.19.100.3
[22-01-2024 01:38:59] INFO: Starts Registration Agent Flow.
[22-01-2024 01:38:59] INFO: Registration Flow - Registration status indicates registration is completed successfully. MPA has nothing to do.
[22-01-2024 01:38:59] INFO: Finished Registration Agent Flow.
[23-01-2024 03:43:21] INFO: SGX Registration Agent version: 1.19.100.3
[23-01-2024 03:43:21] INFO: Starts Registration Agent Flow.
[23-01-2024 03:43:21] INFO: Registration Flow - Registration status indicates registration is completed successfully. MPA has nothing to do.
[23-01-2024 03:43:21] INFO: Finished Registration Agent Flow.
[23-01-2024 03:51:49] INFO: SGX Registration Agent version: 1.19.100.3
[23-01-2024 03:51:49] INFO: Starts Registration Agent Flow.
[23-01-2024 03:51:49] INFO: Registration Flow - Registration status indicates registration is completed successfully. MPA has nothing to do.
[23-01-2024 03:51:49] INFO: Finished Registration Agent Flow.
```

**Comment by xiaoran33** [comment]
> Maybe your platform is not a production platform? What's the uri setting in your PCCS config file? You can try using https://sbx.api.trustedservices.intel.com/sgx/certification/v4/ then restart PCCS service.

**Comment by jsun39** [comment]
would you please do  "SGX Factory Reset" and pasted the log again?  And would you please check the MSR 0x503?

**Comment by xiaoran33** [comment]
> SGX Factory Reset"
I entered BIOS and found that ‘SGX Factory Reset’ is disabled and 'SGX Package Info In-Band Access' is disabled，Do these two options need to be set to enabled?

**Comment by bgotowal** [comment]
Closing due to inactivity after a follow up question has been asked. If you have further questions, please reopen this issue or file a new one.
