### ISSUE TITLE
关于手动启动pccs【dcap1.19】总线错误的问题

### ISSUE THREAD

**Issue by Handikang** [intel/SGXDataCenterAttestationPrimitives#397]
我使用LAZY模式，然后手动启动pccs的时候出现了Bus error (core dumped)
![image](https://github.com/intel/SGXDataCenterAttestationPrimitives/assets/42713276/011748f9-5dc7-4bda-8db2-d74330ada0e6)

而且使用REQ模式的时候出现了下面的错误

**2024-04-30 09:33:08.534 [info]: Client Request-ID : fad8e10374934821a7869e85334d5761
2024-04-30 09:33:08.548 [error]: Error: The platform was not found in the cache.
    at ReqCachingMode.getPckCertFromPCS (file:///home/h/predictor/sd/SGXDataCenterAttestationPrimitives/QuoteGeneration/pccs/services/caching_modes/cachingMode.js:72:11)
    at CachingModeManager.getPckCertFromPCS (file:///home/h/predictor/sd/SGXDataCenterAttestationPrimitives/QuoteGeneration/pccs/services/caching_modes/cachingModeManager.js:54:23)
    at Module.getPckCert (file:///home/h/predictor/sd/SGXDataCenterAttestationPrimitives/QuoteGeneration/pccs/services/pckcertService.js:115:41)
    at async getPckCert (file:///home/h/predictor/sd/SGXDataCenterAttestationPrimitives/QuoteGeneration/pccs/controllers/pckcertController.js:77:25)
2024-04-30 09:33:08.557 [info]: 127.0.0.1 - - [30/Apr/2024:09:33:08 +0000] "GET /sgx/certification/v3/pckcert?qeid=83495CC1CDC5BE73CEF70D7E70611126&encrypted_ppid=B6091754328085362D04F4630969E062E4F6A2DD4256205C786FCE533024138EC83E86942DEE952F4A39487C479267C21C4C9A493E2F2A93751E65C54824681F97CA0D088075B1C1B3F39B44DC422606870F9EF45320D55762E146C21317748DED81CFA35D14811E18E331EFEE7C3FA708ED75C1DD18FA52EC7C61EDE8A74F92DF8728DEE742451510E46CBFABDFB33332AD237FD63287A8F7991E73EB115FF3DD853CE0E4AB22CA87B83865301CB5FC9B10A55B476B5EE90E09A120EC226EBD58E834B7C6E91D627B105295FF8B438C3CC7A8E12CF20FD5A0CF3A96583F25E60079AFF8B6148996CC9A4AA74C158B16766E3CA66E0725AE8D97D0005D0899CDCDCBDC6D315116727AD27DF6CD1C24632505CABD62D06CEAC1CE6A67EF4E433ED323B7CEE332A66D082D333A83A703DFB1BA164E7354945603EBC8E15F4F45DC375700449DF9DFF133CF2E35FAF980A712BD534FDDACAC24B394FC6EA3CB396CB56D6132EF9AA43A28C7FE2DFDD3EF55AC915EA2B46F61CA1C883219BD24C2E1&cpusvn=060D0C0CFFFF00000000000000000000&pcesvn=0F00&pceid=0000 HTTP/1.1" 461 40 "-" "-"**

**Comment by Handikang** [comment]
这个问题已经解决，是因为我没有配置api key ，所以我把issue关闭了
